### ISSUE TITLE
No output is shown from running grunt-cli 

### ISSUE THREAD

**Issue by mwtian-zz** [projectkudu/kudu#1150]
No output is shown on the user side when running grunt-cli in deployment script, or running grunt-cli in debug console.
e.g. in Kudu console, create a tmp folder, and in there, run:

```
npm install grunt-cli
node_modules\.bin\grunt
```

Result: no output is displayed

**Comment by andyseres** [comment]
Hey David - long time!  Cool to see you working on making azure even more awesome.  I wanted to let you know that I ran into this very same issue, and it took me several hours to track this down to use your >out.txt trick which of course told me exactly what the problem was in my grunt assemble step...  Any update on when this'll be fixed so others don't get to run into this too?  thanks....

**Comment by davidebbo** [comment]
Hey Andy, long time indeed!

Sadly, not much progress on this one. Although I did just find one thing: this does not happen when running Kudu locally (i.e. outside of Azure). So maybe something funky with the runtime env on Azure Websites.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
