### ISSUE TITLE
WebJobs: add smarter logic to deal with very long paths

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1239]
In node, a common situation is that some paths are very deep and long, but the files they contain are not actually needed at runtime (e.g. they are often test files).

But this can cause the WebJob to fail to copy to the temp folder (from which we run it). We could have smarter logic to avoid this. Two things to explore:
1. can `\\?\` path be used during the copy operation to get around the 248 char limit?
2. can we simply ignore things that we know won't copy (and print a warning), betting on them not actually being needed at runtime? It won't break anything that's not already broken, and it might unblock many scenarios.

**Comment by albertjan** [comment]
:+1: We're running into this too. We're not running into issues with the copying to the jobs directory. We are running into it when we try to delete jobs, that have very deep pathts, from the jobs directory. I had to use the robocopy mirror with an empty directory trick to remove it in the end.

**Comment by amitapl** [comment]
so copy works but delete doesn't?
what kind of project/site do you have?
can you attach logs if you have them?

**Comment by albertjan** [comment]
Thats what it looks like. We run `npm install` and `npm dedupe` in `\site\repository\jobs\*\` then we run kudusync to sync it to `\site\wwwroot\App_Data\jobs\continuous\*\` and we ended up with a node_modules dir in one of those directories that couldn't be deleted anymore. I'll see if I can reproduce it tomorrow. The logs for failed builds aren't saved, so I don't have those anymore.

**Comment by davidebbo** [comment]
The key is to check whether the longest path length exceeds the 260 char limit. If it does, then it's likely to run into issues.

**Comment by albertjan** [comment]
@davidebbo :smile: I know. Though thats not really an option is it. I want to be able to run my node jobs on azure websites. It's really annoying that npm keeps digging this hole for itself. I don't understand how npm is capable to create these directories. But windows itself can't delete them.

**Comment by davidebbo** [comment]
What I meant is that we first need to identify whether you in fact have paths that exceed that, or whether something else is going on.

**Comment by albertjan** [comment]
Apparently it's not in the deployed site. It's in the `node_modules` directory of our build script. I guess this is not so much a kudu issue but windows/node one. Our buildscript is failing because it's globbing through the directories in search of nuget.exe. But I definitely have paths that are too long though. 

```
rm : The specified path, file name, or both are too long. The fully qualified 
file name must be less than 260 characters, and the directory name must be 
less than 248 characters.
At line:1 char:1
+ rm -r -fo .\node_modules
+ ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (D:\home\site\re...bs\node_modules:S 
   tring) [Remove-Item], PathTooLongException
    + FullyQualifiedErrorId : RemoveItemIOError,Microsoft.PowerShell.Commands. 
   RemoveItemCommand
```

These ar the offending paths: 
 * `D:\home\site\repository\jobs\node_modules\gulp-cucumber\node_modules\cucumber\node_modules\browserify\node_modules\browser-pack\node_modules\combine-source-map\node_modules\inline-source-map\node_modules\source-map\lib\source-map>` 
 * `D:\home\site\repository\jobs\node_modules\gulp-cucumber\node_modules\cucumber\node_modules\browserify\node_modules\insert-module-globals\node_modules\combine-source-map\node_modules\inline-source-map\node_modules\source-map\lib\source-map>`

**Comment by davidebbo** [comment]
Unfortunately, this path limit is deep in Windows, so there isn't much we can do to make these long paths work. The only thing that can be done is to find ways to make the paths shorter (via a mix of dedupe and getting rid of unwanted things), but I realize that is not always practical.

Related to #1490

**Comment by gamicklisafisher** [comment]
I had this problem for a long time.
My friend recommended me Long Path Tool for fixing this.

**Comment by asik** [comment]
Some analysis on this since I just ran into this issue myself:

For nuget packages, using dnx rc1 final, this is the path you have:

    C:\dev\buildagent\_work\ef40a024\a\drop\web\<app-name>\app_data\jobs\continuous\<web-job-name>\approot\packages\<nuget-name>\1.0.0-rc1-final\lib\netcore50\<nuget-dll>

So 120 characters of overhead. Now if you have nuget dependencies with long names like Microsoft.Extensions.Configuration.FileProviderExtensions, your path is:

    C:\dev\buildagent\_work\ef40a024\a\drop\web\<app-name>\app_data\jobs\continuous\<web-job-name>\approot\packages\Microsoft.Extensions.Configuration.FileProviderExtensions\1.0.0-rc1-final\lib\netcore50\Microsoft.Extensions.Configuration.FileProviderExtensions.dll

We're at 238 characters now, and there are probably nugets with longer names than that! That means we only have 22 characters left for the app name + web job name combined. Actually we ran into this using only 18 characters, I am not sure why. 

So *very* little wiggle room and seemingly very few options around this. I'm just crossing my fingers that we don't run into dependencies with longer names yet.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
