### ISSUE TITLE
Support C# 6 on Azure Web Sites

### ISSUE THREAD

**Issue by bojanrajkovic** [projectkudu/kudu#1405]
It'd be nice if WAWS compilation supported C# 6 so that we could start to play with the new features without using Cloud Services/VMs.

**Comment by jaddie** [comment]
Just curious but I am guessing that there is currently no way to use this new code and changes on the live azure websites platform? I only ask because I have written rather a lot of code with the ?. operator in it and if I can avoid having to re-write if its only a day or 2 before this is deployed I'd prefer to do that.

**Comment by ahmelsayed** [comment]
We will probably have the new compiler there by the end of the month depending how the roll-out process goes.

**Comment by mirhagk** [comment]
@jaddie Currently we've switched to manual deployments (using web deploy). Since it's the same .NET framework you can use it.

@ahmelsayed Is there any update on when this will be supported, I'm really hoping I can start using the automatic publishing again (as it's a huge reason why I use azure)

**Comment by ahmelsayed** [comment]
@mirhagk the new MSBuild along with the new C# compiler should be available, but kudu doesn't have any smarts to detect C# 6 projects yet. There is nothing in the csproj itself that tells us the C# version, and I have experimented with detecting VS 2015 projects and assuming they are C# 6, but I haven't made any changes in kudu so far.

If you want to use the new compiler you can put a custom deployment script to your project (`.deployment` and `deploy.cmd`) [that specifies MSBuild path to the new one](https://github.com/KuduApps/CSharp6Web/blob/master/deploy.cmd#L60) check this repo for an example https://github.com/KuduApps/CSharp6Web

**Comment by mirhagk** [comment]
Okay thanks I'll try to get that setup.

Is there any reason why you couldn't just use the C# 6 compiler by default? It's backwards compatible and compiles to the same .NET version so any C# 5 projects won't notice the difference.

**Comment by davidebbo** [comment]
Only reason is fear of bugs and regressions, given that it's not yet full release quality. If we can establish that it's not a concern (not so easy), then we should just move.

**Comment by mirhagk** [comment]
Ahh that makes sense since it isn't full release yet. So it'll switch over once it's declared production ready (I assume with the full release of VS2015).

@ahmelsayed mentioned experimenting with detecting VS2015 projects. I think it's safe to assume that those are C# 6, since even if they aren't the user is using the preview of VS2015 at least. I guess it depend on the effort required vs the predicted release of 2015 (I see most things predicting Q3, but I have a feeling it'll be launched at //build).

**Comment by mirhagk** [comment]
I've used the custom deployment as in https://github.com/KuduApps/CSharp6Web but now we have a problem in that C# 6 has a breaking change w.r.t string interpolation. The latest CTPs have the new syntax `$"hello {name}"` whereas the version referenced by the MSBuild\14.0\Bin path only supports the older syntax of `"hello \{name}"`

At what point does the version get updated, and should we just avoid using string interpolation until release?

**Comment by davidebbo** [comment]
It could be a couple weeks before the new C# 6 CTP gets on there (very rough estimate, could be more or less).

**Comment by ahmelsayed** [comment]
@mirhagk So apparently you can very easily set your project to compile with the C# 6 compiler simply by installing this [nuget package](http://www.nuget.org/packages/Microsoft.Net.Compilers/1.0.0-rc1). After installing it you can get rid of your custom deployment script and it should work when you git push. 
Please give that a try and make sure to get rid of the custom deployment scripts.

**Comment by Korijn** [comment]
Any news now that the release is out?

**Comment by davidebbo** [comment]
This should be available by mid-August. The update is staged, so some scale units will get it before others. If you give a a site name, I can let you know if it has the change or not (but at this point, most don't).

**Comment by deevus** [comment]
How is this going?

**Comment by davidebbo** [comment]
The update is now complete.

**Comment by deevus** [comment]
@davidebbo Is this on all servers? I'm still getting compilation errors with an Azure Website project.

**Comment by davidebbo** [comment]
@deevus  Can you please [share a test repo](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)?

**Comment by deevus** [comment]
@davidebbo I'll see if I can get around to it this week. It's a basic website hosted on Australia East.

**Comment by davidebbo** [comment]
Where it's hosted shouldn't matter, since the servers have the same bits everywhere. What's important is the repo. The test repo we use is https://github.com/KuduApps/Dev14_Net46_Mvc5. It uses a C# string feature [here](https://github.com/KuduApps/Dev14_Net46_Mvc5/blob/master/Dev14_Net46_Mvc5/Controllers/HomeController.cs#L24), and works fine in Azure Web App. Can you try with our test repo and make sure it works for you? Then we can look at your test repo and try to understand why it's broken.

**Comment by deevus** [comment]
Sure. Is there a list of things to check for so that I can troubleshoot? Should I need to change anything to migrate from C#5 to C#6?

**Comment by davidebbo** [comment]
Relating to Azure, there should not be anything special. If it builds on your VS 2015 machine, we expect it to build on Azure Web Apps. If it doesn't, we need to understand why, and that starts by getting a repo that shows the issue.

**Comment by davidebbo** [comment]
@deevus we got a repro from @jonsagara. See #1659 for details and workaround.
