### ISSUE TITLE
Git 2.3 and 'Push to Deploy' feature

### ISSUE THREAD

**Issue by ctolkien** [projectkudu/kudu#1454]
https://github.com/blog/1957-git-2-3-has-been-released

This may simplify the git deployment scenario?  I'm not sure how it would impact Kudu however, just posting as a tracking issue.

**Comment by davidebbo** [comment]
Not sure it would simplify much, because we need to run our hook to do our custom deployment logic. i.e. deploying is more than just checking out the right commit.

One thing I'm confused about is that going to http://git-scm.com/, it shows 2.3 is available, but clicking download on Windows gets you the aging 1.9.5. Do they just not have 2.x on Windows?

**Comment by ctolkien** [comment]
>Do they just not have 2.x on Windows?

That appears to be the case, which is... disappointing.  Will close this as it doesn't sound like it would help to Kudu story much.
