### ISSUE TITLE
Zero Install integration

### ISSUE THREAD

**Issue by bastianeicher** [projectkudu/kudu#1491]
I hope the issue tracker is the right place for this kind of suggestion.

I am a dev on the [Zero Install](http://0install.de/) project, a cross-platform open-source package manager. Its main feature is the ability to "run" applications without having an explicit install step (automatically downloading and caching any required binaries and dependencies for you).

I think this makes it a great fit for custom deployment scripts and/or the debug console. The main use-case I see is the ability to quickly get additional dev-tools (such as Maven or CMake) pulled into the environment on a per-user basis.

Currently a user can do something like this in the debug console:
```
curl -O http://0install.de/files/zero-install.zip
unzip zero-install.zip
0install run cmake
```
I would love to talk about options for getting this more tightly integrated, perhaps by adding Zero Install to the VM image.

**Comment by davidebbo** [comment]
From doing a quick test, the download and unzipping of Zero Install using the steps above happens pretty quickly, so the experience is not so bad. What I would suggest is to first advertise this workflow with users to get a sense of how many Azure Websites users are interested in doing this.

Then if it reaches some good level of popularity and users are asking for simpler steps, we can consider deeper integration onto the VM.

I'm closing this here since it is not strictly speaking a Kudu related. Can you add this instead as a suggestion [here](http://feedback.azure.com/forums/169385-web-sites/)? This way others get to vote for the idea.
