### ISSUE TITLE
Go: able to config logging to file system as well as blob storage

### ISSUE THREAD

**Issue by shrimpy** [projectkudu/kudu#1535]
Need to implement something similar to "nodejs interceptor" for Go

**Comment by dstpierre** [comment]
@shrimpy I'm Dominic from [this SO question](http://stackoverflow.com/questions/34322855/how-to-tail-log-from-go-app-on-azure-web-app/) 

So would that be something I could contribute for Kudu, instead of handling my own logging for Go app in Azure?  Where is this "nodejs interceptor", maybe that could give me a basic idea of what's required.

Do you think this task is small enough for a first contribution?

**Comment by shrimpy** [comment]
@dstpierre thanks for your offering to contribute. 

RE: Do you think this task is small enough for a first contribution?
[shrimpy] it is hard to say how difficult the task will be, and i haven`t done any further investigation. 
Different technologies need to be handled differently. We have rich support for .net tracing, where trace can go to FileSystem/Blob/Table storage, and for NodeJS we only support FileSystem via a customer version of [interceptor](https://github.com/tjanczuk/waws-interceptor) i believe.

For Go, the challenge is to find out is how to redirect standard output, which would be very different from what was done for .net and nodejs. So there is not much to reference.

So if you are doing your own tracing, what library will you use? The easy approach we might just bring in an opensource library to do that with come customization.

**Comment by dstpierre** [comment]
Well I would personally not use any external Library, the log package seems to be enough [well for my own usage]. Since we can change its output to be a file, it might be enough as a starting point. Couple of question if I may?

1. So is it Kudu that is responsible to start the process for HttpPlatformHandler? From what I was thinking Azure was kind of grabbing the stdout / stderr of the running process and was itself writing to files in LogFiles/Application directory and this is what get tail when using `azure site log tail sitename`.  Did not thought it was handle differently for different technologies.

2. Might be basic question but are the Go app `azureapp.exe` that gets build after a git push do have write access to LogFiles/Application than?  Because in that case I would just write the clean-up code to make sure log files are rolling over just like the custom Node interceptor. Is the `tail` command simply listen to file changes in LogFiles/Application and writes them to console?

For now my needs are very basic, and similar feature to what I had with Node would be enough for now, so without rewriting anything from my app, which already use the Go core log package, I think I might just pipe the output to files in the LogFiles/Application and create a simple package that takes care of cleaning those files.

If the `azureapp.exe` do not have write access, than, if my question 1. is positive and Kudu do start the process, than it might have a way to grab stdout / stderr from there and write into the log files. But I've read your documentation yesterday and it seems Kudu have the same permissions than the web app itself.

If you can confirm that I'm in the right direction assuming that once there would be file written in LogFiles/Application they will get tail by the azure CLI, than I can maybe write a small package that could eventually be able to write to Blob, I'm already using [azure-sdk-for-go](https://github.com/Azure/azure-sdk-for-go) which works nicely for Blob.

Also what about multiple app instance, are the LogFiles/Application shared across all app instance, we current have 2 and will soon scale to 3 instance, does that have any impact on log files?

Thanks for your time

**Comment by davidebbo** [comment]
Kudu is not in the picture for `HttpPlatformHandler`, not is it responsible for writing to `LogFiles/Application`. Kudu does *consume* the content of this folder for log streaming, but something else at runtime needs to write to it. Yes, that folder is writable to you.

Try the following fun test which will help understand things:

- Run `azure site log tail sitename`
- In [Kudu Console](https://github.com/projectkudu/kudu/wiki/Kudu-console), go to `D:\home\LogFiles\Application`
- Run `touch foo.txt` to create an empty file, and click the edit button next to it
- Write some text in there and hit Ctrl-S. Each time you save, you should see the new content being display by the tail command.

Yes, all instances share the same `LogFiles/Application`. Recommendation is to use the first 6 characters of %WEBSITE_INSTANCE_ID% as part of your log file name to help differentiate. The streaming will include all files in that folder, regardless of their name.

Does this help?

**Comment by davidebbo** [comment]
You do raise a good point about how this could be automatic if the stdout/stderr of HttpPlatformHandler was automatically written there. I think it's a worthwhile idea to consider (/cc @ranjith-r).

**Comment by davidebbo** [comment]
Per http://www.iis.net/learn/extensions/httpplatformhandler/httpplatformhandler-configuration-reference, `HttpPlatformHandler` already has support for this via `stdoutLogEnabled` / `stdoutLogFile`. However, in my initial testing, I could not make it work reliably. It seems out the output gets buffered and is not written to the file until I touch web.config, which doesn't make sense...

**Comment by shrimpy** [comment]
David and I tried playing around with HttpPlatformHandler, seems like ```` stdoutLogEnabled / stdoutLogFile ```` works in a strange way, where standard output did write to log file, but file metadata (file size, modify date) doesn`t always change (/cc @ranjith-r). 

The above issue will cause "LogStream" feature not working properly. As for actual logging, you can reference custom web.config from below repository. And you will need to manual download the file to see the log as for now.

https://github.com/shrimpy/HelloGoApp

**Comment by dstpierre** [comment]
thank you @davidebbo @shrimpy this all got more clear for me suddenly, the `stdoutLogEnabled / stdoutLogFile` is promising though, but for immediate debugging need I think I will just directly write into the `LogFiles/Application`.

Unless you think the stability of the `HttpPlatformHandler` stdout capturing could be something that can improved in a somewhat not far future?

**Comment by shrimpy** [comment]
@dstpierre i would suggest you to directly write output to ``` LogFIles/Application ``` for now.  (```LogFIles/Application``` folder is not there by default, make sure you have code to create folder if not existed)

**Comment by dstpierre** [comment]
will do, might even wrap it into a Go Azure log package and share it than, since I need to write it for our SaaS. Thanks again for your time, appreciate it.

**Comment by davidebbo** [comment]
I came up with an alternate (temporary) solution that works with the current platform handler. See https://github.com/davidebbo-test/ConsoleInterceptor for details.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
