### ISSUE TITLE
Running deployment script as admin

### ISSUE THREAD

**Issue by michaldudak** [projectkudu/kudu#1590]
I'm not even sure if this is possible in any way - I'd like to permanently set environment variables during web app deployment. To do this, the script must run with elevated privileges. Can this be achieved? (I tried to install ASP.NET's 5 DNVM and it crashed while trying to set the path)

**Comment by suwatch** [comment]
Is this in the Azure env?   If so, you could use WebApps' appSettings.    Is this env variable only known during deployment time?

**Comment by michaldudak** [comment]
Yes, I'm running this on Azure. The script I want to run sets the PATH variable (not sure I can set PATH from web apps' settings) and yes, its value is known only during deployment.

**Comment by suwatch** [comment]
Let me make sure, I get your scenario right.  You mentioned `I tried to install ASP.NET's 5 DNVM`.   You are doing that during deployment (via deployment script), correct?   The installation of such in turn set the global %PATH% variable and it failed, correct?

**Comment by michaldudak** [comment]
Yes, I have a custom deployment script (based on the one generated by `azure site deploymentscript` command) that tries to install DNVM as described in https://github.com/aspnet/Home/blob/dev/README.md. The dnvm.ps1 script that runs in the process (https://github.com/aspnet/Home/blob/dev/dnvm.ps1) calls `[Environment]::SetEnvironmentVariable("PATH", $userPath, "User")` and fails, throwing "Exception calling "SetEnvironmentVariable" with "3" argument(s): "Requested registry access is not allowed."

**Comment by ahmelsayed** [comment]
since deployment happens in the context of a webapp, you can't set global environment variables. It's more complicated than just allowing you to run scripts as admin. Since you can scale your app up and down or to run on 1 VM or 20, we will need a way to roam the settings you set during deployment to all of these instances on demand. So just allowing you to set the global path isn't sufficient. 

As for dnvm, we already support deploying beta 4 ASP.NET 5 webapps out of the box. [Here is a sample repo](https://github.com/ahmelsayed-test/HelloWeb) If you just push this repo to a newly created site it will build and deploy successfully. You can take a look at the deployment script we auto generate in that case, but it basically looks something [like this](https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.aspnet.5.template)

**Comment by michaldudak** [comment]
Thanks a lot, it works indeed!

**Comment by ahmelsayed** [comment]
Awesome! I'm glad it worked :+1:

**Comment by michaldudak** [comment]
I just put together an article about continuous deployment of ASP.NET 5 apps, in case someone else has this problem: http://blog.dudak.me/2015/deploying-asp-net-5-application-to-azure-web-app-using-git-or-mercurial/

**Comment by davidebbo** [comment]
Nice, thanks for sharing!
