### ISSUE TITLE
You are running kudu against a local kudu service and are not an Administrator.

### ISSUE THREAD

**Issue by paranoid-android** [projectkudu/kudu#1611]
I have tried setting up Kudu in my local development environment at `http://localhost.com:91`. When I visit that URL, I get the following error:

```
You are running kudu against a local kudu service and are not an Administrator. Re-run this process as Administrator in order to continue.
```

How do I resolve this? Is this a bug? What process is being referred to? Is it the kudu.web process or the kudu.service process or both?

**Comment by ahmelsayed** [comment]
It's the Kudu.Web process. Basically Kudu.Web gives you a small `inetmgr` like web-interface for creating and managing sites that have Kudu.Service.Web setup correctly for. 
You can skip that if you know how to set it up manually with inetmgr, but Kudu.Web makes it a lot simpler. Since Kudu.Web manages your IIS, it needs to run elevated.

**Comment by paranoid-android** [comment]
@ahmelsayed  - So, how do I run the site elevated?

**Comment by ahmelsayed** [comment]
If you're running it from Visual Studio, you'll have to run VS itself as Admin. 
If you set it up in IIS, you'll need to set the Application Pool identity to LocalSystem.

**Comment by paranoid-android** [comment]
@ahmelsayed Awesome! Thanks for your help.
