### ISSUE TITLE
Basic ASPNET 5 CI Deploy Failing

### ISSUE THREAD

**Issue by sethjuarez** [projectkudu/kudu#1730]
I yo-ed up a new ASPNET 5 application and attempted a CI deploy through Github without success (got YSOD). Here are the pertinent links:

* Github Project: https://github.com/sethjuarez/SuperWebApp
* Azure Website: http://superwebapp.azurewebsites.net/
* Video Repro: https://youtu.be/zwkQesiCdbQ
* dnvm alias command returns 
     * alias: default 
     * name: dnx-clr-win-x86.1.0.0-beta7  
     * orphan: False

Any ideas?

**Comment by davidebbo** [comment]
If you turn off customer error, the failure is:

    Could not load file or assembly 'Microsoft.Dnx.Host.Clr' or one of its dependencies. The system cannot find the file specified.

I think we might have seen that before. @ahmelsayed ?

**Comment by ahmelsayed** [comment]
This is happening because Kudu is installing `1.0.0-beta6` runtime which is what we default to if the repo doesn't specify a runtime. We should probably update that to beta7.
The way to specify that in your repo is to create a `global.json` file in the root of your repo and have this in it

```json
{
  "sdk": {
    "version": "1.0.0-beta7"
  }
}
```

Now if you do that in your repo, you'll hit this issue https://github.com/aspnet/dnx/issues/2656 and to work around that you'll have to move all the files in your repo under a sub folder, and have `global.json` in the root

**Comment by davidebbo** [comment]
Who owns this Yeoman generator? It's unfortunate that what it generates by default is broken.

**Comment by snobu** [comment]
Here it is https://github.com/yeoman/yo/issues/

**Comment by ahmelsayed** [comment]
I think that's the base generator itself. Each project implements a generator for itself, and I think this is the ASP.NET 5 one https://github.com/OmniSharp/generator-aspnet

**Comment by ahmelsayed** [comment]
I'd think that they may wanna fix the generated project to use a certain runtime, but then again things are moving fast with the beta releases and they break compat all the time. I don't know if moving forward they expect backward compatibility in which case they'll be okay with always defaulting to the latest framework in the generator.
