### ISSUE TITLE
Cannot handle long file paths.

### ISSUE THREAD

**Issue by ericterpstra** [projectkudu/kudu#1757]
I've been using Kudu successfully for a few days to deploy a Meteor app on Window Server 2012. Recently, though, a package I added to my app has a ton of nested npm dependencies, and when I deploy, I get this:

```
Invalid path for filesystem 'D:/kudu/apps/scorecard/site/repository/bundle/programs/server/npm/tdamsma_meteor-accounts-ldap/node_modules/activedirectory/node_modules/bunyan/node_modules/mv/node_modules/rimraf/node_modules/glob/node_modules/minimatch/node_modules/brace-expansion/.gitattributes': The data area passed to a system call is too small.\r\n
```

In order to get commits working in Git, I had to use Git Bash and run the command:

```
git config core.longpaths true
```

After that, I can push & pull from GitHub & Bitbucket.  Is there any way to fix this in Kudu?

**Comment by shrimpy** [comment]
windows has path limit of 260 character unless [it is a network path](https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx). And your file path seems to have 265 characters.

Even if Kudu can do similar config on libgit2sharp, git library kudu is using, at the end file and folder will be created on windows file system, your deployment will fail due to the file path limit.

You might want to look for ways to reduce the length of the file path.

**Comment by ericterpstra** [comment]
npm3 will allegedly help to flatten the node_modules folder (which will help me, at least), but it's not released yet.

I'm using Git-Bash to deploy manually, and it works fine.  If Kudu/libgit2sharp will not support longpaths, then I guess I'll have to wait.

**Comment by shrimpy** [comment]
@ericterpstra 

npm3 seems already released https://www.npmjs.com/package/npm

````
3.3.8 is the latest of 169 releases
````

**Comment by ericterpstra** [comment]
@shrimpy That's correct. Using npm3 is a good solution.  Unfortunately for me, Meteor bundles an older version of node and npm in its installer, so when it pulls packages from npm, the old nested structure is used.  I'll close this, since it's really a Meteor issue rather than Kudu.
