### ISSUE TITLE
Ability to initiate a timed network trace

### ISSUE THREAD

**Issue by kamranayub** [projectkudu/kudu#1864]
I'm not sure if this is possible, but it would be nice to somehow allow capturing network traces so I can diagnose connection issues to external services. As long as there's a pcap or cap file at the end, I'll be satisifed.

**Comment by davidebbo** [comment]
Interesting idea. I'm guessing some tools wouldn't agree with the sandbox. But note that `curl` has some good tracing options which could be used to diagnose some issues (well, at least for http scenarios).

**Comment by kamranayub** [comment]
I haven't looked at that yet--in my case, RavenDB is issuing network requests that are throwing exceptions and they'd (support team) prefer a network trace to diagnose. But I don't think I can capture it in Azure. It would also cover non-HTTP traffic--i.e. web sockets.

**Comment by snobu** [comment]
I second the initiative to provide packet capture ability.
I think it's fair to expect PCAP being the norm and the desired output.

My Windows networking skills are not very sharp but i think it's doable in one of these 2 ways. There could be more, these are the ones i used a lot.

#### netsh trace ####
Produces __ETL__ traces. ETL can then be converted to PCAP with Microsoft Message Analyzer (http://blogs.technet.com/b/yongrhee/archive/2013/08/16/so-you-want-to-use-wireshark-to-read-the-netsh-trace-output-etl.aspx). Would be nice if we could have this in the pipeline so the resulting capture out of Kudu would be PCAP and not something intermediary. No idea if Message Analyzer can be automated that way.

```
C:\>netsh trace start capture=yes IPv4.Address=192.168.122.2

Trace configuration:
-------------------------------------------------------------------
Status:             Running
Trace File:         C:\Users\Administrator\AppData\Local\Temp\NetTraces\NetTrace
.etl
Append:             Off
Circular:           On
Max Size:           250 MB
Report:             Off

C:\> netsh trace stop
Correlating traces ... done
Generating data collection ... done
The trace file and additional troubleshooting information have been compiled as
"C:\Users\Administrator\AppData\Local\Temp\NetTraces\NetTrace.cab".
File location = C:\Users\Administrator\AppData\Local\Temp\NetTraces\NetTrace.etl

Tracing session was successfully stopped.
```

#### TShark with WInPcap ####
https://www.wireshark.org/docs/man-pages/tshark.html

WInPcap is required and needs to be installed in the OS. Installs as a service. We can start/stop on demand since it doesn't make sense to drag it around in memory 24/7 even if the memory footprint is minimal.

```
C:\WINDOWS\system32>net start npf
The NetGroup Packet Filter Driver service was started successfully.
```

Both methods require things to happen in a different security context than what the sandbox provides.
Wireshark/tshark.exe can run without elevation but WinPcap needs to be started as a service first.

**Comment by snobu** [comment]
The ultimate cool this for this would be to have a Profiler-like UI flow. You click on **Start trace**, do your thing, click Stop, you get the `.pcap` file as a download. And we just force-stop the capture after 7-10 minutes if the user got distracted.

![image](https://cloud.githubusercontent.com/assets/6472374/16363639/8f8bb30c-3bd9-11e6-93ef-3a891064d295.png)

**Comment by davidebbo** [comment]
Agreed, that would be cool.

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
