### ISSUE TITLE
Parameters.xml in Kudu

### ISSUE THREAD

**Issue by ricardopolo** [projectkudu/kudu#1905]
Hello.

I am trying to solve this issue http://stackoverflow.com/questions/35529052/how-to-define-connection-string-for-session-state-in-azure

Keeping in mind that the azure settings become enviroment variables, I tought you can use `parameters.xml` using a procedure like this https://www.appveyor.com/docs/deployment/web-deploy#parameters-xml.

`Parameters.xml` allows you to modify the `web.config` based on environment variables. The thing is this work when i manually publish from my computer or using another CI server like Appveyor, but using kudu `parameters.xml` are ignored.

Do you know why?

Thanks!

**Comment by davidebbo** [comment]
I think the problem is that `parameters.xml` is an msdeploy concept, and msdeploy is not used in Kudu. What Kudu does is equivalent to a Deploy To File System in VS. So you can use that to test your deployment outside of Kudu. See [this page](https://github.com/projectkudu/kudu/wiki/Make-sure-site-correctly-deploys-locally#locally-testing-your-deployment) for more info.

**Comment by davidebbo** [comment]
Not exactly the same thing, but also look into this technique: http://brian.vallelunga.com/blog/chaining-azure-web-config-transforms-when-deploying-from-source-control

**Comment by ricardopolo** [comment]
I did it using this 
http://stackoverflow.com/questions/35529052/how-to-define-connection-string-for-session-state-in-azure/35641453#35641453
