### ISSUE TITLE
Azure deployment nodejs x64

### ISSUE THREAD

**Issue by francesconero** [projectkudu/kudu#1914]
Is there a way to use a 64 bit nodejs binary when building node modules during deployment?

It seems that trying to use a downloaded x64 nodejs binary to issue the npm install still fails on subequents node-gyp calls, which resort back to using the global command `node` (which points to `D:\Program Files (x86)\...`).

I ask this beause some native modules need the 64bit binary to correctly be built. (for example [lovell/sharp](https://github.com/lovell/sharp))

**Comment by snobu** [comment]
We run node through iisnode. This should do it:

https://azure.microsoft.com/en-us/documentation/articles/nodejs-specify-node-version-azure-apps/

> Create an iisnode.yml file in the same directory as the server.js file, and then add the following content to the iisnode.yml file:
`nodeProcessCommandLine: "D:\home\site\wwwroot\bin\node.exe"`
This path is where the node.exe file within your project will be located once you have published your application to the Azure Website.

However since you seem to hit that problem at deployment time you probably need to alter the `PATH` env var and add the path to your x64 binary before the x86 node stuff.
https://github.com/projectkudu/kudu/wiki/Xdt-transform-samples

**Comment by ahmelsayed** [comment]
I think @francesconero is referring to npm building native modules. I made a fix which puts the VC++ compiler and a bunch of other lib and h files on azure VMs to support building native npm modules but I only included the files needed for building x86 modules because I figured we don't even have x64 bit node on the server. @francesconero are you bringing your own node runtime?

**Comment by snobu** [comment]
Right. I remember that. Referencing the issue for context: https://github.com/projectkudu/kudu/issues/1076

**Comment by francesconero** [comment]
@ahmelsayed yes, exactly, @snobu sorry if I wasn't clear. If I remember correctly, I tried to issue a npm install through a downloaded x64 node executable. I gave up pretty quick though, since it's easier right now to just build on an external windows machine and just copy the node modules over.

**Comment by Freundschaft** [comment]
its still a pain, I'm trying to deploy https://github.com/lovell/sharp to my azure app, which is only readily available for x64 windows.
I can replace node with the 64 bit version, but npm will still be stuck with 32 bit :(

**Comment by yaoyel** [comment]
@Freundschaft   same problem with me ,did you solved it?

**Comment by Freundschaft** [comment]
in the end the only soltuion that worked for me was to upload the compiled binaries directly instead going through NPM, back then I wasnt able to find a more elegant workaround, not sure if something changed now.

**Comment by snobu** [comment]
Now there's App Service on Linux workers and you can bring your own Docker container or use the_blessed_ ones that come with the service. The service is generally available and offers SLA.

**Comment by Freundschaft** [comment]
ah nice, that makes totally sense, docker solves a lot of problem for you in that case

**Comment by eatfrog** [comment]
bumping this since ive struggled with the same problem all day. eventually i tried the app service on linux with docker, but the node image seems to lack python so i still cant build sharp. what a total nightmare this seemingly easy thing has turned out to be.

has anybody found a solution that doesnt involve uploading compiled binaries?

**Comment by snobu** [comment]
Build your own container, import from a node one, add the python deps and publish to either Dockerhub or [Azure Container Registry](https://azure.microsoft.com/en-us/services/container-registry/).

**Comment by rand0me** [comment]
Thanks for working suggestion, but does someone cares about fixing this bug?

For me, using Linux App Service is not an option, because it lacks of Consumption Plan (which is required in my project). Neither I want to upload a compiled binaries and create child process and other shims and hacks.

:relaxed:

**Comment by thomas-mindruptive** [comment]
Hi,
is there already a solution apart from uploading my "own" nodejs.
Thanks

**Comment by suwatch** [comment]
We are currently making certain 64 bits nodes available on Azure App Service VM.   Anyone would be able to use it.  @mhoeger can provide more details (ETA, what versions etc).

**Comment by thomas-mindruptive** [comment]
Thanks a lot, in the meantime It tried:
@mhoeger 
- Upload node 10.15.3 64 bit via kudu to d:\home\node-10.15.3
- Set languageWorkers:node:defaultExecutablePath containing that path in azure portal, section "configuration"
- added iisnode.yml pointing to new node-10.15.3. to my deployment
- restarted app
- redeployed via git (local rep): during the process, kudu correctly recognizes the node version in iisnode.yml (output says: "the iisnode.yml file explicitly...") but the node install process still uses "...\program files(x86)..."

thanks

**Comment by mhoeger** [comment]
@thomas-mindruptive - Ashley Grant's recommendation here should be helpful! https://github.com/Azure/azure-functions-nodejs-worker/issues/158#issuecomment-480023626

As a note, we do currently have one 64-bit node version deployed (mainly for testing before we switch logic) try changing `languageWorkers:node:defaultExecutablePath` to `D:\Program Files\nodejs\10.15.2` and it should work. 

I'll update this thread later with details on how the official support works when it is ready!

**Comment by thomas-mindruptive** [comment]
@mhoeger 
Thanks, I changed the `languageWorkers:node:defaultExecutablePath` as mentioned but get the same errors

`ERR! sharp Windows x86 (32-bit) node.exe` ...
...
`remote: gyp ERR! command "D:\\Program Files (x86)\\nodejs\\10.14.1\\node.exe" `

Should I change the path env-variable or create a ".deployment" file maybe?

Thanks and best

**Comment by thomas-mindruptive** [comment]
PS: If I remove `WEBSITE_NODE_DEFAULT_VERSION` from the app configuration (so `languageWorkers:node:defaultExecutablePath`) is the only setting pointing to a node version/path, I get errors containing the path `D:\Program Files (x86)\npm\1.4.28\node_modules...`. So it falls back to an old npm/node version.
Best

**Comment by thomas-mindruptive** [comment]
Sorry to bother you again. Found a way it works:
Set `WEBSITE_NODE_DEFAULT_VERSION` to `D:\Program Files\nodejs\10.15.2`, too.
Thanks and best
Thomas

**Comment by jvano** [comment]
Hi

Kudu will continue to run in Azure App Service. However, this repo will no longer be maintained.
If the problem persists and is related to running on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
