### ISSUE TITLE
[Webjob / Go] error loading zoneinfo.zip

### ISSUE THREAD

**Issue by dstpierre** [projectkudu/kudu#1921]
We are getting an error running a go app as a webjob the time zone info files cannot be found:

open c:\go\lib\time\zoneinfo.zip: The system cannot find the file specified.

I've then added the ZONEINFO environment variable to the current executing path and embedded the zoneinfo.zip file. But I'm still getting this error.

I guess Go is not installed on the VM? What are my options here?

Also when deploying a Go app to app service, how can I tell the current version Azure is supporting? I've read in your announcement that you were handling 1.4.1 and 1.5.1, but is 1.6 now available, how to specify this, is it still in GOROOT app's application settings as a configuration variables?

Is there a documentation similar to this for Go at the moment? https://azure.microsoft.com/en-us/develop/

Thanks for your time

**Comment by shrimpy** [comment]
@dstpierre 

I think the issue here is there is no GOROOT defined in the environment. .
Kudu only temporary define GOROOT and Go workspace in deployment time in order to build Go webapp.

RE:  how can I tell the current version Azure is supporting?
From DebugConsole, navigate D:\Program Files\Go, you will see all the version we support. 
Currently we try to only keep one latest version for each major version (1.4, 1.5, 1.6), since once a Go app is built, it does not depends on Go binary anymore.

When reference a Go binary, will be good to always reference the latest version. Below PS script is what Kudu [use](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Scripts/selectLatestVersion.ps1) to find out latest version as default version during deployment time.

Let me know if this script can be incorporate with your application as work-around,  if not, open an issue for us, we can have a GOROOT environment variable point to the latest version of GO. 


RE: Is there a documentation similar to this for Go at the moment?
We do not have much documentation at this point, but we are here to answer questions.

Hope this will solve your issue.

````
<#
this script takes in two param, target folder path and output file path
what it does is, it assume immediate sub folder of target folder are all name with version
and this script is trying to get the folder name has the largest version
#>

PARAM(
	[parameter(Position=0, Mandatory=$true)]
	[string]$folderPath, 
	[parameter(Position=1, Mandatory=$true)]
	[string]$outputPath
)

$latestVersion =
	Get-ChildItem "$folderPath" |
	Where-Object {$_.Name -as [Version]} |
	Sort-Object -Property @{e={[Version] $_.name};Ascending=$false} |
	Select-Object -First 1 |
	Select Name -ExpandProperty Name

[System.IO.File]::WriteAllText("$outputPath", $latestVersion)

EXIT 0
````


![image](https://cloud.githubusercontent.com/assets/79823/13649347/28792aa6-e5f2-11e5-8953-0c3f7bd3641a.png)

**Comment by dstpierre** [comment]
Yes, the missing GOROOT in application settings fixed this, thank you and thanks for the other clarification.
