### ISSUE TITLE
RBAC access role for Kudu WebJob logs

### ISSUE THREAD

**Issue by RonakThakkar** [projectkudu/kudu#1931]
Hi,

I would like developers in my organization to be able to access Kudu and See WebJobs logs.

I assigned them Reader role and they are not able to access these logs. If I assign them Contributor Role they can access, but then they have more control over managing resources on Azure which I would not like to have them.

Is there any RBAC role in Azure that can help me satisfy these need.

**Comment by suwatch** [comment]
Unfortunately, there isn't such role yet.   

One way if you really need to and not too big a hammer, instead of accessing Kudu directly, to use [ARMClient](https://github.com/projectkudu/ARMClient).   The reader would be able to access Jobs and history via `.../sites/{siteName}/triggeredWebJobs/{jobName}` etc.  For continuous webjob, use `continuousWebJobs` instead.  Hope this helps.

**Comment by davidebbo** [comment]
I also want to clarify

> If I assign them Contributor Role they can access, but then they have more control over managing resources on Azure which I would not like to have them

If you make them contributor to just the Web App, then they don't have access to any other Azure resources. They have full access to the site, but since your goal is to give them Kudu access, and Kudu can already do anything it wants to the site, I wouldn't think this is an issue.

**Comment by RonakThakkar** [comment]
I assign them website contributor role from new azure portal and that worked fine.

**Comment by gregjhogan** [comment]
@davidebbo @suwatch I am trying to use the ARM APIs to read the output log for a web job run.  Is that possible?

I can get a run with this URL:
```
https://management.azure.com/subscriptions/{subscription-id}/resourceGroups/web-test/providers/Microsoft.Web/sites/test-web-app/triggeredWebJobs/test-job/history/201708032224361073?api-version=2016-08-01
```
but that is just the run metadata, and I want the output log.

Thanks!

**Comment by davidebbo** [comment]
@gregjhogan the output log is not exposed over ARM, though it is available from the [Kudu API](https://github.com/projectkudu/kudu/wiki/WebJobs-API).

**Comment by gregjhogan** [comment]
@davidebbo but the Kudu API requires the Contributor role on the web app?  I want people to be able to see the logs, but not the connection strings, etc...  Thanks!

**Comment by gregjhogan** [comment]
Also, I can't figure out what permission is needed for reading the history (Reader role isn't sufficient, and it doesn't tell you what permission you need)
```
.../sites/{site-name}/triggeredWebJobs/{jobs-name}/history
```

**Comment by davidebbo** [comment]
Indeed, you won't be able to access the full logs from Reader role. Part of the reasoning is that those logs may contain sensitive data output by the WebJobs (e.g. connection strings), and exposing them to Readers can cause as escalation of privilege. Note that readers don't have access to App Settings & Connection Strings for the same reason.

**Comment by raje678** [comment]
@davidebbo 

Hello,
I am trying to figure out the way for to access the ARM template Outputs in Kudu deployment/post deployment scripts.  If I use the powershell script cmdlets to query the outputs, it is throwing Login-AzureRmAccount error. I am not sure how the azure session information shared between ARM and KUDU. My scenario is as below:

My web app build code is in Github and using the deploy to Azure button for to invoke the ARM template for to create the resources and doing the deployment from Github repository using the ARM sourcontrols type. In order to take the control of deployment process, I have wrote my own .deployment and calling my custom deploy.cmd/ps1.

Can you provide me the correct syntax to pull the ARM outs to powershell/batch script with out logging into powershell again because at the time of invoke the deploy to azure button I already logged in? I am not sure how the session information share between ARM template and .deployment scripts.

**Comment by davidebbo** [comment]
@raje678 your question does not sound related to this issue, and is probably an App Service question not really related to Kudu. Please use StackOverflow or the App Service MSDN forum instead.

**Comment by hosseinjayride** [comment]
I have the exact same problem, but I don't find any solutions in this thread. Our developers need to see the logs in order to debug their code, but giving them full access to Kudu is not desirable for obvious reasons.

@gregjhogan How can logs include connection strings? Is it something done by the job runner or you mean if a developer adds a line of code in the job to see the connection string (something like `Console.WriteLine(AppSettings["ConnectionString"])`)? Developers use different types of logging to print out the required info in order to debug their code. All these logs go to the Web Jobs logs in Kudu. To me, it doesn't make sense if they can't see the output of their own code. At least it can be the policy of a company. If they trust that their developers don't write anything like `Console.WriteLine(AppSettings["ConnectionString"])`, then why should they block their access to the logs completely?

Besides, how come there are RBAC roles to read the data that is logged in Application Insights, but not the Web Jobs Logs? What's the difference? Can a developer log a connection string or anything in App Insights?

**Comment by ericy99** [comment]
I agree this is a high demand role to at least allow developer read log. Obviously website contributor is too powerful for such purpose.  It is 2020 now, do we still not have a solution?
