### ISSUE TITLE
Improve the error handling when site extension installs fail via ARM

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#1987]
In [this code](https://github.com/projectkudu/kudu/blob/f155220791f19d7d00d24afe7ba2caa3dae18bc3/Kudu.Core/SiteExtensions/SiteExtensionManager.cs#L450), we send back a very generaic message with no info about the actual exception, amkingmaking it hard to diagnose.

**Comment by CamyDee** [comment]
The more detail you can provide to the caller, the better. There are many things in play here, and without direction as to what is going wrong, the client in shooting in the dark. Because deployment is such a critical path, I think this issue is extremely important.

Also, in this particular instance... consider a feature where you detect when shadowing is turned off on the webapp, and stop the website prior to deploying. Perhaps gated with a 'force' parameter?

**Comment by davidebbo** [comment]
Let's track anything beyond error reporting separately to keep issues clean. But do note that the deployment process does not have the ability to shut down the site.

We'll improve error reporting.

**Comment by CamyDee** [comment]
sounds good. 👍

**Comment by shrimpy** [comment]
Fixed in https://github.com/projectkudu/kudu/pull/1992

**Comment by davidebbo** [comment]
The fix is now deployed to Azure.
