### ISSUE TITLE
WEBSITE_TIME_ZONE not respected for scheduled WebJob

### ISSUE THREAD

**Issue by cincuranet** [projectkudu/kudu#1988]
Setting the `WEBSITE_TIME_ZONE` to some value in Azure portal (in my case `Europe Standard Time`) does not reflect this in the schedule of scheduled WebJob (using `settings.job` file). The job is still triggered based on UTC timezone.

Screenshots from Kudu:
![image](https://snag.gy/0kYD46.jpg)
![image](https://snag.gy/c9J15P.jpg)

**Comment by davidebbo** [comment]
Did you verify that the time zone you set is in fact effective if you just run `time` from Kudu Console? If not, then the issue is lower level (maybe invalid time zone string), and not WebJobs related.

See https://github.com/projectkudu/kudu/wiki/Configurable-settings#set-the-time-zone for more info.

**Comment by cincuranet** [comment]
Mea culpa. I really did write `Europe Standard Time`, while it should have been `Central Europe Standard Time`.
