### ISSUE TITLE
There is not enough space on the disk. 

### ISSUE THREAD

**Issue by SebastianStehle** [projectkudu/kudu#2091]
Hi,

some days ago my deployment stopped working. When I clicked to the deployment source settings it was just empty with a "rain" icon.

Today I tried to disconnect and to setup it again and then I got the following error:
Failed to set up deployment source for web app mockit, using GitHub. Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: There is not enough space on the disk. 

I have not changed that much in  the last couple of days, e.g. no big npm package or something like this. But I deploy usually once a day.

There are 400MB for deployment logs :/

**Comment by davidebbo** [comment]
400MB for deploy logs sounds abnormally large. Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by SebastianStehle** [comment]
The name is "mockit" 

I already deleted the log files hours ago and tried to setup the deployment again. But it fails now with "An unknown error has occurred. Check the diagnostic log for details." after the deployment command.

**Comment by davidebbo** [comment]
And to make sure, are you talking about logs that were in `D:\home\site\deployments`, or something else? It would have been interesting to see what was taking so much space. We only keep the last 10 deployments, and the log for each shouldn't be more than a 100KB or so.

As for your new error, where exactly are you seeing it? Is that something in the Azure Portal? Can you include a screenshot to illustrate?

**Comment by SebastianStehle** [comment]
it think it was D:\LogFiles\Deployment. attached is the screenshot

![untitled](https://cloud.githubusercontent.com/assets/1236435/17208605/af7224f0-54b9-11e6-9575-7ed8bcb19f39.png)

**Comment by davidebbo** [comment]
`D:\LogFiles\Deployment` is not a folder that normally exists. If you run into this again, let's take a closer look at the files that take space.

Looking at your site, I see the last deployment is successful, so I think we can close this issue.

**Comment by SebastianStehle** [comment]
It is not successful, the version is one week old.

**Comment by davidebbo** [comment]
I think what's going on is that the deployment is causing the CPU (or memory) quota to be reached, causing the site (and Kudu) to be killed. Is the site/Kudu accessible at all after the failure?

Note that is you run on a Basic/Standard site instead of Shared, there are no quotas (only VM limitations).

**Comment by SebastianStehle** [comment]
The site is still accessible, havent realized a shutdown. And what I dont understand is, that the hard work has been done in the "Running deployment command" step.

**Comment by simax** [comment]
Hey David,

I'm getting exactly the same issue. I'm currently on the free tier (which is about to expire tomorrow!) but after attempting a lot of deployments I'm now getting the error telling me: `There is not enough space on the disk` 

I'm going to have to upgrade my plan tomorrow because my 30 days are up (30 days is nowhere near long enough.) 

That said, will upgrading prevent the error condition? 

`Failed to set up deployment source for web app PowershopAzureImages, using GitHub. {"Code":"BadRequest","Message":"Repository 'UpdateSiteSourceControl' operation failed with System.Net.WebException: There is not enough space on the disk.\r\n     at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r\n   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)\r\n   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)\r\n   at System.Xml.XmlWriterSettings.CreateWriter(String outputFileName)\r\n   at ...
`

**Comment by davidebbo** [comment]
@simax yes, upgrading to Basic or Standard will very likely avoid this issue.

**Comment by spsandrew** [comment]
@davidebbo We have a deployment running on Standard 2 and are seeing this issue.

**Comment by davidebbo** [comment]
@spsandrew this is a very old issue, so best to open a new one. But first, check whether you may actually be out of disk space.

**Comment by kamesh-git** [comment]
I had a linux operationg system and an windows OS in same machine via dual boot and for linux OS i made a seperate partition of 200GB from my from 1TB hard disk. Few weeks ago i deleted my 200GB linux partiton via disk management in windows and the 200GB space become unallocated but i can't able to merge or extend the partition the error it shows is 
there is not enough available space on the disk 

![`there is not enough available space on the disk`](https://i.stack.imgur.com/gA6LQ.png)



i opened the diskpart in cmd and tried to list volumes and partition in that but i couldn't able to view my unallocated partition

![`diskpart`](https://i.stack.imgur.com/LuEiL.png)

![`unallocated partition`](https://i.stack.imgur.com/O1f04.png)

kindly help to resolve this issue i want to either extend my partition or make it a new simple volume
