### ISSUE TITLE
Support .NET Core deployment with multiple projects in a SLN

### ISSUE THREAD

**Issue by jsgoupil** [projectkudu/kudu#2116]
Before .NET Core, I have been using the Application Settings in the Azure Portal called "Project"
It points to ".csproj" so it knows to deploy that particular project.

Now, when using a "Project", with a xproj, we get the following:
The specified project '...\Web.xproj' is not valid. It needs to point to either a csproj/vbproj file or to a directory.

I see a lot of talking about this "global.json". This seems to be the new to support deploying a particular project to Azure. This will conflict with existing website projects that are using the "Project" settings for deployment in the Azure Portal.

**Comment by davidebbo** [comment]
Hey JS. Our Core support is still fairly new and there are some rough edges. @watashiSHUN is working on some Core deployment script changes as part of #2111, and we can think about this scenario as well.

Note that for now, you can probably make this work using a custom deployment script.

**Comment by watashiSHUN** [comment]
Hello JS, according to [kudu wiki](https://github.com/projectkudu/kudu/wiki/Customizing-deployments#deploying-a-specific-aspnet-core-project), in order to deploy an ASP.NET core project
you need to "specify the path to the folder that contains the project.json"

could you try this: 
Azure Portal --> Application settings --> App settings --> Project =  **directory path** to the project.json file, relative to the root of your repo.

**Comment by jsgoupil** [comment]
Thanks @watashiSHUN . This is working.
@davidebbo Apparently it's covered. But only the directory, not the file itself.
