### ISSUE TITLE
Packaged Installer

### ISSUE THREAD

**Issue by hitchhiker** [projectkudu/kudu#2144]
Hi,

Been using Kudu for years, can't live without it. Deployment to a server is ridiculously laborious though, is there any chance we'll get a nice packaged installer in the future?

**Comment by davidebbo** [comment]
Indeed, it's not an area that we're investing much in. Realistically, for something to happen here, someone from the community would need to pick that up.

The closest thing we have today is the dev setup script and custom WebPI feed in https://github.com/projectkudu/kudu/tree/master/Setup. That's tailored to the dev machine scenario, but a variant of it could be adapted to set up servers.

**Comment by hitchhiker** [comment]
That's a shame, it's getting harder and harder to install every year.. now the various GIT/NODE combinations are starting to cause strange problems. The various packages we need to install before are getting complicated. The guides appear to be out of date, or not present for the basic server setup also. I'm not a noob, been using servers since win NT days.

**Comment by davidebbo** [comment]
It should not be getting harder. Can you give more details about the specific issue you are having? We can update the [steps](https://github.com/projectkudu/kudu/wiki/Deploying-to-a-server) if there are specific things that can reduce confusion.

**Comment by kamranayub** [comment]
I am new to setting up Kudu and was following the steps in the Wiki.

I had to make some changes and am still setting up the environment to work (so I will update as I fix things):

- [x] Instead of compiling locally, I used the "kudu.zip" from the GH releases
- [x] I had to install 32-bit Node.js (but 64-bit Git seems to work)
- [x] I had to update Kudu.Services.Web\bin\Nuget.exe to 3.x (it was at 2.8 and failed to download some packages)
- [ ] I am now getting an error from Nuget about not being able to access LocalSystem profile folder

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
