### ISSUE TITLE
Webjobs Publish package fails to deploy Azure Scheduler with a null reference error

### ISSUE THREAD

**Issue by anblanco** [projectkudu/kudu#2159]
I'm noticing that when I try to deploy a scheduled webjob (using Azure Scheduler), i'm getting an error and the schedule does not deploy.
...
Publish Succeeded.
Creating the scheduler job
...\packages\Microsoft.Web.WebJobs.Publish.1.0.12\tools\webjobs.console.targets(110,5): Error : An error occurred while creating the WebJob schedule: Object reference not set to an instance of an object.

When I try it for my MSDN subscription, things work correctly, but when I try it on my work subscription (which has policies to prevent Classic ASM objects from being created), I get this error. I see the webjob, and scheduler job collection, but no scheduled job.

**Comment by davidebbo** [comment]
All the scheduler aspect is not part of Kudu. But note that the recommended approach is to use the Kudu CRON approach instead of the Azure scheduler, which shoudl avoid all these issues. See [doc](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/#CreateScheduledCRON) for details.
