### ISSUE TITLE
Webjob published to a deployment slot fails to create/update schedule

### ISSUE THREAD

**Issue by pizerg** [projectkudu/kudu#2161]
For more details see this issue [http://stackoverflow.com/questions/31680673/azure-webjobs-publishing-error] , this has been around and not fixed since version 1.0.4 of WebJobs.Publish package for Visual Studio 2013 and for all versions of the package for VisualStudio 2015 as it refuses to work with package 1.0.3 which worked properly on Visual Studio 2013.

**Comment by davidebbo** [comment]
That logic is actually not part of Kudu (it relates to VS configuring the Azure Scheduler, which is a separate piece).

But note that for scheduling WebJobs, the recommended approach is to use the Kudu CRON scheduler instead of the Azure Scheduler. This solves all these issues. See [doc](https://azure.microsoft.com/en-us/documentation/articles/web-sites-create-web-jobs/#CreateScheduledCRON) for details.
