### ISSUE TITLE
Kudu debug console in Azure Portal

### ISSUE THREAD

**Issue by johnknoop** [projectkudu/kudu#2197]
Hi

How come the Kudu debug console is different from the console found in the Azure portal for an app service? The Kudu console seems more feature complete (support for tab completion etc).

Will Kudu ever get integrated into the Azure Portal, or is the plan to keep it outside as it´s own thing? I understand there may be different teams developing these products, but from a users perspective, it would be nice to have everything in one place.

**Comment by davidebbo** [comment]
The one in Portal is actually using the Kudu API (command controller) under the cover. The difference is that it doesn't use SignalR, and instead uses a single command mode which makes it less of a true console. e.g. you run `set foo=1`, and it's not actually there, whereas is Kudu Console it is.

I think the reason we couldn't use the SignalR flavor in the Portal is that Portal had concerns over keeping on open connection to the backend, due to the limited number of connections made available by browsers.

Note that Portal does have a direct link to Kudu Console, under Advanced Tools.
