### ISSUE TITLE
is_in_place and UpdateAppConfigAddTraceListeners caused cyclic of Change notification

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#2205]
For C# with *.exe.config, we are injecting appSettings, connectionStrings as well as traceListeners ([here](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Jobs/BaseJobRunner.cs#L377) and [here](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Jobs/BaseJobRunner.cs#L444)) to the job *.exe.config file.   If is_in_place is true, this causes an infinite cyclic of change notification, job startup and inject config.

We discovered this when cleaning up the Kudu error.   For internal reference, [site info] (https://observer/sites/id/13596425).   

The suggested fix would be to, after update the config, only save the file if content has changed.   This would cause the one extra change notification - trade off with simplicity.

**Comment by davidebbo** [comment]
In the in-place case, the intention is that the config injection should not happen at all. Under no circumstance should we modify the user deployed files. I think that it already worked like that way back, but maybe got regressed. In any case, we just want to disable this behavior completely for in-place.

Functionally, it's not a big deal, because in-place is more for Node, which doesn't benefit from this mechanism anyway. In-place is a bad choice for .NET, as it keeps files locked.
