### ISSUE TITLE
Output of .NET Core CLI is not displayed

### ISSUE THREAD

**Issue by fabiocav** [projectkudu/kudu#2294]
When running the "dotnet" (by simply typing `dotnet` in the diagnostics console, CMD or PowerShell), the output briefly flashes on the screen and disappears.

**Comment by davidebbo** [comment]
They seem to do some weird CR/LF things that confuse Kudu console. You can even repro like this:

- Run: `dotnet > out.txt`
- Run: `type out.txt`

If you look at out.txt, instead of having `0x0d 0x0a` line ending sequences, it has doubled Carriage Returns before the Line Feed: `0x0d 0x0d 0x0a`. And for some reason that makes Kudu console behave funny.

@ahmelsayed I'm thinking it's something we could fix on Kudu side? We could report as dotnet issue, but the fact is that it appears to be harmless in a regular console, so in that sense it is our bug.

**Comment by ahmelsayed** [comment]
we interpret alone `\r` as a line clear command, so when we get `\r\r\n` we interpret that as clear the line, then move to the line below. This was done because that's how curl outputs download progress indicator.
I think that was just nice to have, but I'm not sure why few tools output things in that format. So far I know of typescript compiler and now dotnet.exe

**Comment by davidebbo** [comment]
Cool. Did you test both curl and dotnet, to make sure there is no noticeable regressions?

**Comment by ahmelsayed** [comment]
yep, tested curl with 
`curl -o file.zip https://functionsbay.blob.core.windows.net/public/1.0.0.beta.9/Azure.Functions.Cli.zip`
and dotnet just by listing the help.

**Comment by watashiSHUN** [comment]
it looks like the [fix](https://github.com/projectkudu/kudu/blob/42317ae0116b689be06b305d495267d0654b0707/Kudu.Services.Web/Content/Scripts/KuduExecV2.js#L228-L230) is checking `(current line ends with "\r" && last line equals "\r\n")`, if the condition is `true`, we will **not** skip current line
This will not work for `tsc --version` since it output like this:
![capture](https://cloud.githubusercontent.com/assets/6531400/21967306/0edbc42c-db39-11e6-9c0d-d5d9ba2da4e0.JPG)

I used another command line exe to test (`youtube-dl`...a little tool that I used to download video, of cause with the progress indication) since `curl` **does not hit the line being changed**: rather than outputing `"progress 10%\r" "progress 11%\r"` it is doing this `"progress 10%" "\r" "progress 11%" "\r"`
