### ISSUE TITLE
Linux: Incorrect permissions on SSH keys.

### ISSUE THREAD

**Issue by jackturnbull** [projectkudu/kudu#2310]
Discovered when attempting git based deployment that uses private repo within NPM.

Relevant part of the logs:
```
remote: npm ERR! Bad owner or permissions on /home/6431f78a17d565eb48d79cd2/.ssh/config
remote: npm ERR! fatal: Could not read from remote repository.
remote: npm ERR!
remote: npm ERR! Please make sure you have the correct access rights
remote: npm ERR! and the repository exists.
remote: npm ERR!
remote: npm ERR!
remote: npm ERR! If you need help, you may report this error at:
remote: npm ERR!     <https://github.com/npm/npm/issues>
```

I'm going to take a guess that its because the ssh keys have been created with no owner, or at least not the correct owner which I'm assuming to be '6431f78a17d565eb48d79cd2' in this case.

```
/home>ls -la 6431f78a17d565eb48d79cd2/.ssh
total 5
drwxrwxrwx 2 nobody nogroup    0 Jan 26 10:52 .
drwxrwxrwx 2 nobody nogroup    0 Jan 26 10:51 ..
-rwxrwxrwx 1 nobody nogroup   34 Jan 26 10:52 config
-rwxrwxrwx 1 nobody nogroup 1679 Jan 26 10:52 id_rsa
-rwxrwxrwx 1 nobody nogroup  380 Jan 26 10:52 id_rsa.pub
```

The public key itself works no problem when pulling the repo's on my local machine so I feel like it's only permission based.

**Comment by nickwalkmsft** [comment]
Hey @jackturnbull,

This is a known issue with Kudu on Linux at the moment. A fix is forthcoming.

ssh does an extended check on ~/.ssh/config and halts if the owner or permissions aren't what it expects; see the "Files" section at the very bottom of the ssh_config man page. Due to the way the environment is set up, it's not possible to change the owner or permissions on files in /home. chmod and chown will fail silently.

A fix is forthcoming. Although I haven't tested it, an interim workaround that should work is to use the Kudu Bash console to delete /home/$KUDU_RUN_USER/.ssh/config, and add an entry to the known_hosts file for the remote server. A limitation of this is that Kudu will recreate the config file if you ever regenerate the key, which will happen if you disconnect/reconnect to source control, but you should be able to operate without it as long as there is a known_hosts entry for the remote.

**Comment by elmo61** [comment]
I've had this problem also, but was unable to get it working, tried the method above and got past the inital problem but ended up with a host key verification failed problem. 

Do you have any updates on this? it seems odd that Github deployment was added to App Service Linux without it ever working.

**Comment by nickwalkmsft** [comment]
@elmo61, we have a candidate fix in place, not in Kudu but in the Kudu container setup. I'm not sure of an ETA for rollout yet.

The problem is constrained to usage of ssh (which was working originally until a regression was introduced), so Github deployment from a non-private repo still just works, as Kudu uses HTTPS by default. We don't distinguish strongly enough between private and non-private in the implementation to explicitly enable one and not the other in the Azure portal.

I just walked through the following workaround steps and successfully synced a private repo:

- Start with a Linux site not connected with source control. If your site is connected and you disconnect it via the portal, this will remove the .ssh folder and its contents in the Kudu user's home dir.
- Use the portal to connect to your private repo. This will recreate the .ssh dir with a new public/private key and a new config file, add the new key as a deploy key to your private repo, and perform a sync (which will fail, due to the "Bad owner or permissions" error).
- Open the Kudu console and run the following. This will delete the config file that fails the permissions check and create a known_hosts entry for Github:
  - _rm /home/$KUDU_RUN_USER/.ssh/config_
  - _ssh-keyscan -t rsa -H github.com > /home/$KUDU_RUN_USER/.ssh/known_hosts_
- Go back to the portal and sync source control. This should succeed.

If you disconnect/reconnect source control, you'll need to follow these steps again.

**Comment by elmo61** [comment]
Thanks for the feedback it has been helpful, looking forward to the actual update to linux app service.

**Comment by nickwalkmsft** [comment]
Fix is live. CI from private repos and any other repository accessed via ssh is enabled.
