### ISSUE TITLE
Sync function triggers should happen when using the vfs/zip APIs

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2357]
Today, when vfs or zip APIs are used, the function triggers are not synced, leading to multiple reported cases of user function apps not waking up.

We should consider adding logic that calls `/operations/settriggers` when those APIs are called on function apps.

**Comment by davidebbo** [comment]
@suwatch, does that require FE changes so it would pass the restricted JWT for those? Or does Kudu always get it?

**Comment by suwatch** [comment]
It would require FE change to pass the restricted JWT for those scenarios.   I assume the vfs and zip apis were called explicitly by users (not via certain portal gestures).   There are a few options we could consider.

  - Document only.   Tell user that they also need to call functions/synctriggers in addition of vfs or zip (or even FTP).

  - Add these scenarios for FE to pass JWT token + Kudu fix to consume.   Given uncommon and simple workaround (above), users could wait for Antares release cycle for the fix.

  - We could generalize such that, for dynamic, PUT/PATCH/DELETE verbs will get token (not a day-to-day operations) and certain POST that we already knew of + Kudu fix to consume token.

Since you had to open the issue, I assume we must do something and the 2nd option seems proportional at this point.

**Comment by davidebbo** [comment]
I think in the two cases I saw, people were doing command line automation, and using vfs to upload their function files. Workaround is indeed to explicitely do a sync, and I have a [PowerShell sample](https://github.com/davidebbo/AzureWebsitesSamples/blob/fbbbbfdbeb0fc1f42b5c9b15df8adadd1457a5f6/PowerShell/HelperFunctions.ps1#L350-L355) to point them to.

Yes, I think Option 2 is good, even if it takes a while to propagate.

**Comment by suwatch** [comment]
Tracked for next Azure WebApps release (addressing just vfs and zip).

**Comment by npiasecki** [comment]
Is there any documentation as to what syncfunctiontriggers actually does?

The reason I ask is I stumbled across this from [here](https://social.msdn.microsoft.com/Forums/azure/en-US/026fb46d-f341-448e-96e4-1702a6f9a4b0/azure-functions-stop-working-job-thread-was-being-aborted?forum=AzureFunctions) after porting the workers (cron jobs in Quartz) of one of our on-premises apps to Functions hosted in an app service plan, and my build server deploys them with WAWSDeploy. Some of the functions can be longish running (like 5-10 minutes), and I noticed that whenever I did a deploy, or App Service boots me to another VM, things would go sideways for 10-20 minutes. Specifically, I get hammered with lots of "Thread was being aborted" or weird errors where AppSettings return null. Looking at the Functions logs, I would see weird patterns of the host keep getting restarted.

I ran syncfunctiontriggers before my deployment and did it after deployment and am knocking on that that fixed it, but am also not sure if it's actually fixed. Does syncfunctiontriggers have something to do with making sure functions aren't fired during a host shutdown or at the wrong time? Thank you.

**Comment by davidebbo** [comment]
@npiasecki synctriggers is only meaningful when using Consumption. So if you're using App Service Plan, this is definitely unrelated to what you are seeing.

**Comment by npiasecki** [comment]
@davidebbo Thank you! Knowing that and looking back it, I *think* it was caused by my deployment not containing a host.json, and I had WAWSDeploy set to delete files that aren't in the source to keep things tidy. 

Reading the log, deleting host.json triggered a host shutdown immediately. (I guess the WAWSDeploy deletes files first, then goes to upload, and that took longer than the debounce of 500 ms that I see in the code.) The host started up and then started noticing assembly changes as WAWSDeploy went to the upload stage, so it shut itself down and restarted again. This would lead a flurry of errors in my log since it was a short-lived host. Adding a host.json in my deployment seems to have nixed the double startup issue. 

(I think the issues with landing on a new VM causing errors is that I just need to deal with some of my long-running functions being a little quicker to shutdown, as they're used to an environment where the worker basically never shut down.) Thanks for confirming that for me, and I'll stop spamming this issue!

**Comment by davidebbo** [comment]
@npiasecki seems like a plausible theory. You probably should include a host.json in your deployment to avoid this. It can be as simple as `{}`.

**Comment by gorillapower** [comment]
Is this still in the pipeline? I am running a consumption plan azure function from a package and I am doing a VFS deployment to still be able to do a custom deployment.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
