### ISSUE TITLE
Exception while parsing function triggers should result in a failed deployment

### ISSUE THREAD

**Issue by davidebbo** [projectkudu/kudu#2429]
Right now, they get ignored, leading to hard-to-find issues like #2428. We need this to be a hard failure so the user knows something is wrong.

**Comment by davidebbo** [comment]
@suwatch, given that this is part of `PostDeploymentHelper`, do you think it's possible (and advisable) to make it fail the deployment if something fails?

**Comment by suwatch** [comment]
Yes, it is possible (simply throw).   Advisable or not, I am not sure.  Perhaps, it should so it will not be silent/hidden for starter or give wrong impression to users that everything is fine.

**Comment by watashiSHUN** [comment]
if we throw, it will fail the deployment, but since [we don't log the status of `SyncFunctionsTriggers`](https://github.com/projectkudu/kudu/blob/master/Kudu.Core/Deployment/DeploymentManager.cs#L631-L633)
the result from git command line will look like it's a success:
> 	2017-05-09T21:53:57.6758834Z,Copying file: 'step2\sample.dat',,0
	2017-05-09T21:53:57.7696973Z,Restoring npm packages in "D:\home\site\wwwroot",,0
	2017-05-09T21:54:16.2527327Z,npm WARN paymentfunctions@ No repository field.,,1
	2017-05-09T21:54:16.3919719Z,npm WARN paymentfunctions@ No license field.,,1
	2017-05-09T21:54:16.5222663Z,Finished successfully.,,0
2017-05-09T21:54:16.8138816Z,Running post deployment command(s)...,4f2450d9-68b6-4e56-a5c9-4b1fee93b213,0

**only if you look into it**, you will find the actual deployment status:
![throw](https://cloud.githubusercontent.com/assets/6531400/25876757/3f1c5fe4-34d4-11e7-8fcd-71ee8002f851.JPG)

**Comment by suwatch** [comment]
@watashiSHUN we should have traced the error to logger.   Try debug and see why?

**Comment by watashiSHUN** [comment]
![nologex](https://cloud.githubusercontent.com/assets/6531400/26021489/678b9be0-3743-11e7-9e50-a7e7f3e0810c.JPG)

@suwatch this is the output after fix, do we want to display more information? the stack trace seems to be only available in the trace file

**Comment by suwatch** [comment]
@watashiSHUN that's a good starter.    BTW, when ILogger logs the information/error, it returns inner ILogger.   You could you that to log exception.  UI wise, I believe it will show up in view log.

```csharp
ILogger Log(string value, LogEntryType type)
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
