### ISSUE TITLE
Web Apps: choose a specific instance to connect to

### ISSUE THREAD

**Issue by benaichouchem** [projectkudu/kudu#2436]
It would be nice to have the ability to select a Web App instance to run against. This is handy to profile a specific instance

**Comment by benaichouchem** [comment]
If I get some guidance, I would love to implement this feature :)

**Comment by davidebbo** [comment]
It's actually possible using the ARRAffinity cooker. See http://blog.amitapple.com/post/2014/03/access-specific-instance/ for more details.

But note that Kudu itself cannot choose the instance, since it's already running inside one instance.

**Comment by benaichouchem** [comment]
Hi @david there is even a better approach to do it from the browser and setting the ARRAfinity cookie, but was wondering if I can list all instances for a web app. So this is not achievable?

**Comment by davidebbo** [comment]
@benaichouchem the way to get the list of instances is via the ARM API. e.g. go to https://resources.azure.com/ and look at the 'Instances' API under any Web App. But the problem is that you can't call the ARM API from Kudu, unless you explicitly set up a service principal that you pass in via App Settings (difficult and wouldn't work in the general case).

I think the best bet would be to add UI in the Azure Portal that would let you select which instance of Kudu you want to run. But that's not something that Kudu itself can implement.

**Comment by snobu** [comment]
An alternative approach would be to write a browser extension for both Chrome and Edge that does exactly that (grabs all instance ids from ARM and injects the right cookie on the fly). Amending the Portal UI is clearly the better choice though.

**Comment by davidebbo** [comment]
@snobu that would be cool, but the hard part is for the extension to get an ARM token so it can make those calls.

**Comment by TeplrGuy** [comment]
@davidebbo is there any new on this feature? New UI has this feature but for some odd reason when user selects a specific instance to SSH into, the hostname of that machine is different. User is in an ASE

**Comment by suwatch** [comment]
add @sanchitmehta.  Share the UTC time when you tried, instance id and site name [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly).

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
