### ISSUE TITLE
Cannot deploy netcoreapp2.0

### ISSUE THREAD

**Issue by jaredcnance** [projectkudu/kudu#2511]
### Repro steps.
> your project built successfully on your dev machine but failed on Azure?

yes

> please write down your build tools and their versions (ie `Msbuild 15.1.0.0`)

```
λ dotnet --info
.NET Command Line Tools (2.1.0-preview1-006923)

Product Information:
 Version:            2.1.0-preview1-006923
 Commit SHA-1 hash:  775ebc5e56

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.0-preview1-006923\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.0
  Build    : e8b8861ac7faf042c87a5c2f9f2d04c98b69f28d
```

### Project structures.
> in order to reproduce your issue at our end we need a simple github repository
> that highlights structure of the project

See: [dotnet-status](https://github.com/jaredcnance/dotnet-status/tree/master/api)

### The log/error given by the failure.
> Normally this include a stack trace, error code and some more information.

```
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.
  - Check application dependencies and target a framework version installed at:
      \
  - Alternatively, install the framework version '2.0.0'.
```

Location South Central US
URL http://dotnet-status.azurewebsites.net

This service was previously running a version against netcoreapp1.0 so, I also tried deploying to a new App Service which did not change anything.

**Comment by davidebbo** [comment]
So the deployment succeeds, but it breaks at runtime? Note that Core 2.0 has not yet been released. The latest on App Service is `2.0.0-preview2-25407-01`.

See https://github.com/davidebbo-test/AspNetCore20Preview2 for a sample 2.0 preview app that deploys and runs successfully on App Service.

**Comment by watashiSHUN** [comment]
Your error message implies that there is no dotnet core framework installed (possibly because it is not looking on the right folder), should be `D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App` instead of `\`

Also I failed to look for your website, is it removed?

**Comment by jaredcnance** [comment]
@davidebbo that is correct and I am aware that 2.0 is preview which is why this is not a huge concern for me and I posted here rather than opening a support ticket.

@watashiSHUN that makes sense, should I be setting an env var pointing to the correct location? yes, the website was removed. The link above points to a new service I created to ensure that it had nothing to do with the fact that there was a previous version targeting netcoreapp1.0. The current version is at http://dotnet-health.azurewebsites.net (with a CNAME to dotnet-status.com)

**Comment by alexvy86** [comment]
Having the same issue. @watashiSHUN why would the environment be looking at `\` instead of the correct path? I can see the subfolder for `2.0.0-preview2-25407-01` under `D:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App`, and AFAIK I've never told my app to look at any non-default locations for anything.

Also for the record, I thought it might have to do with the Azure region since my app is deployed in South Central US, just like @jaredcnance 's, but I tried deploying it to Central US and I got the same error.

**Comment by alexvy86** [comment]
@davidebbo I just tried publishing the [sample app you mentioned](https://github.com/davidebbo-test/AspNetCore20Preview2) and it's giving me the same error :), you can see it [here](http://preview2-testapp20170802031200.azurewebsites.net/). Sounds like something in the environment is not working correctly...?

![image](https://user-images.githubusercontent.com/716334/28893058-b5414dde-7795-11e7-876f-a61f4ab9b65f.png)

**Comment by davidebbo** [comment]
Strange, as that works for me:

```
D:\home\site\wwwroot>dotnet Preview2-TestApp.dll
Hosting environment: Production
warn: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to bind to http://localhost:5000 on the IPv6 loopback interface: 'Error -4090 EADDRNOTAVAIL address not available'.
Content root path: D:\home\site\wwwroot
Now listening on: http://localhost:5000
Application started. Press Ctrl+C to shut down.
```

Can you share the name of your test web app where it doesn't work?

**Comment by alexvy86** [comment]
Sure, [preview2-testapp20170802031200](http://preview2-testapp20170802031200.azurewebsites.net/)

**Comment by alexvy86** [comment]
I'm working with Visual Studio 2017 15.3 Preview 6.0, publishing from Solution Explorer by right-clicking->Publish on the project.

As for the dotnet sdk, I have these installed:
![image](https://user-images.githubusercontent.com/716334/28895920-ec6c0588-779f-11e7-9cc7-891a66b7d021.png)

**Comment by alexvy86** [comment]
On related topics, the section for **.NET Core** [here](https://github.com/projectkudu/kudu/wiki/Azure-Web-Sites-Development-Stacks) is outdated, right? At least 2.0.0-preview2 should be there as well?

**Comment by davidebbo** [comment]
@alexvy86 note that if you deploy from VS, you are not using Kudu. Kudu is about git pushing to Azure and having it build the project there. I'll try that scenario from VS.

I corrected the supported version, thanks.

**Comment by alexvy86** [comment]
Good point. I'll have to make some changes to my solution in order to try it with Kudu, since I have a local project outside the repo that I'm referencing as a dependency (and which should really be just a DLL reference but I'm also following up on [another issue](https://github.com/dotnet/core-setup/issues/2113) to figure out why a simple DLL reference makes an ASP.NET Core application with MVC crash at runtime).

**Comment by davidebbo** [comment]
FYI, looks like there is a Preview 7 now. Not saying it's going to make a difference, but may as well have the latest just in case.

**Comment by alexvy86** [comment]
I saw it when I was checking my current version but didn't want to install anything that might change my environment before any troubleshooting that might need to take place. And nothing in the release notes seemed particularly relevant to me hehe. I'll probably give it a couple of days and then install it.

**Comment by alexvy86** [comment]
Btw, I'm interested to know if you're able to publish the sample app from VS, so when you have a chance to try that, please let us know how it went :)

**Comment by davidebbo** [comment]
I just did. Specifically:

- I updated to Preview 7 (I was super far behind)
- I opened my test project https://github.com/davidebbo-test/AspNetCore20Preview2
- Published it to a new app service and it runs fine: http://tmpcorepreview2.azurewebsites.net/
- Manually running `dotnet Preview2-TestApp.dll` from Kudu also works

**Comment by alexvy86** [comment]
Huh... which dotnet sdk do you have installed?

**Comment by alexvy86** [comment]
Also, any chance you could share a zip file with the files that were deployed to the test Web App, so we can compare with ours? I've published to different Plan levels, 3 different regions... and still the same problem. Sounds like an issue with my local build environment, so maybe looking at the differences between the built projects could help me pinpoint what exactly is different.

**Comment by davidebbo** [comment]
Here is what I have under `\Program Files\dotnet\sdk`.

![image](https://user-images.githubusercontent.com/556238/28900190-5287171e-77a4-11e7-8d5d-98cc6f359875.png)

Here is what I have in my deployed wwwroot on Azure: https://davidebbostorage.blob.core.windows.net/public/tmpcorepreview2.zip

**Comment by alexvy86** [comment]
Ah, how fun... I tried the same thing with your sample app in another computer and it worked. \*Sigh\*... At least I now have two environments to compare, I'll report back once I figure this out, in case it helps @jaredcnance .

**Comment by davidebbo** [comment]
BTW, I installed sdk 2.0.0-preview2-006497 and that didn't make a difference. But I see you also have some 2.1.0 build, in case that matters.

**Comment by jaredcnance** [comment]
@alexvy86 mine was deployed using the VSTS deployment mechanism which I'm assuming is the same one VS uses? So my problem may not be kudu related. Not really sure where to go to track that down then. Thanks for all your hard work guys.

**Comment by alexvy86** [comment]
Success! Indeed @davidebbo, in my case the 2.1.0 dotnet sdk was the problem. With it installed, the `<app-name>.runtimeconfig.json` file in the published output was getting the framework version set to `2.0.0` instead of `2.0.0-preview2-25407-01`. 

![image](https://user-images.githubusercontent.com/716334/28900825-8f58625a-77b9-11e7-93a6-d65d6014f7aa.png)

Using a [global.json](https://docs.microsoft.com/en-us/dotnet/core/tools/global-json) in the project folder to force the "preview form" made the published sample app run successfully in App Service, and uninstalling the 2.1.0 preview had the same effect.

@jaredcnance I guess the build process in VSTS might be similar to the one VS uses, but I'd look into what versions of the tools (e.g. the dotnet sdk) exist in their build servers, since they might not match your local environment, thus creating builds that won't run as a local one would. Maybe try publishing directly from VS into a new WebApp, to see if that works? I would be surprised if the VSTS build servers have the 2.1.0 preview SDK, so my guess is that the issue in your case is not **exactly** the same, but might also have to do with tool versions.

**Comment by alexvy86** [comment]
@watashiSHUN, I guess the error message which supposedly indicated a wrong path was not quite right after all... it was probably looking in the right location but (correctly) not finding the `2.0.0' subfolder. In which case the error message might have a bug?

**Comment by davidebbo** [comment]
@alexvy86 great, glad we got to the bottom of this mystery! I'll close the issue then.

**Comment by watashiSHUN** [comment]
@jaredcnance @alexvy86, I just tested by deploying a 2.0.0 project to kudu, it failed at deployment, which is expected since we don't yet have 2.0.0 **SDK** (tooling to build):
```
remote: ..................
remote:   Restoring packages for D:\home\site\repository\shuntest.csproj...
remote: D:\home\site\repository\shuntest.csproj : error NU1102: Unable to find package Microsoft.AspNetCore.All with version (>= 2.0.0)
remote: D:\home\site\repository\shuntest.csproj : error NU1102:   - Found 3 version(s) in nuget.org [ Nearest version: 2.0.0-preview2-final ]
remote:   Generating MSBuild file D:\home\site\repository\obj\shuntest.csproj.nuget.g.props.
remote:   Generating MSBuild file D:\home\site\repository\obj\shuntest.csproj.nuget.g.targets.
remote:   Restore failed in 3.12 sec for D:\home\site\repository\shuntest.csproj.
```

for your case, you actually have a successful build (binaries), but because Azure does not yet have the 2.0.0 **runtime** you are basically using an old dotnet clr to run your latest dll : `dotnet(2.0.0 preview1) website.dll(2.0.0)`. and my test gives me this error:
```
It was not possible to find any compatible framework version

The specified framework 'Microsoft.NETCore.App', version '2.0.0' was not found.

  - Check application dependencies and target a framework version installed at:

      \

  - Alternatively, install the framework version '2.0.0'.
```
we are deployment the **runtime** and **sdk** next week, so for now you can do a [self contained app](https://github.com/dotnet/docs/blob/master/docs/core/deploying/index.md#self-contained-deployments-scd) (ouputing an .exe instead of .dll) if you want to test 2.0.0
