### ISSUE TITLE
WebJob is stopping due to website shutting down

### ISSUE THREAD

**Issue by dmytro-gokun** [projectkudu/kudu#2514]
Our setup is following:

1) A WebApp on Basic plan with "Always On" = true;
2) A continuous WebJob.

Every 20 minutes or so, the WebJob gets restarted. The log shows this:

[08/05/2017 16:45:40 > b6e2f1: SYS INFO] WebJob is stopping due to website shutting down
[08/05/2017 16:45:40 > b6e2f1: SYS INFO] Status changed to Stopping
[08/05/2017 16:45:45 > b6e2f1: ERR ] Thread was being aborted.
[08/05/2017 16:45:45 > b6e2f1: SYS INFO] WebJob process was aborted
[08/05/2017 16:45:45 > b6e2f1: SYS INFO] Status changed to Stopped
[08/05/2017 16:45:58 > b6e2f1: SYS INFO] Status changed to Starting
[08/05/2017 16:45:58 > b6e2f1: SYS INFO] WebJob singleton setting is False
[08/05/2017 16:46:01 > b6e2f1: SYS INFO] Run script 'Processor.exe' with script host - 'WindowsScriptHost'
[08/05/2017 16:46:01 > b6e2f1: SYS INFO] Status changed to Running

Any ideas how to prevent this. The continouos job should not be restarted (it runs long background tasks which cannot be restarted, job restart means the task has to be restarted from the beginning).

**Comment by davidebbo** [comment]
Can you share your web app name, either directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly)? This will help us investigate. Thanks!

**Comment by dmytro-gokun** [comment]
I've created dummy1066.azurewebsites.net on the same app service plan.

A small note here. Yesterday, after posting this question, I removed the long job from the queue and then WebJob would not restart again. Today, I've queued this job again and I see a restart again. This gives us a hint: could it be that website is being shut down because of the webjob's high CPU/memory usage?

**Comment by davidebbo** [comment]
@dmytro-gokun I investigated, and that is exactly what's happening. You're on a small VM, and I see processor.exe with a high working set (e.g. 1089 MB) is one sample reading around that time. The overall VM memory gets too high, and the system chooses to shut down the site (and hence the WebJob).

Your options are:

1. If possible, reduce memory usage of processor.exe
2. If that is not an option, you will need to upgrade to a Medium worker

**Comment by dmytro-gokun** [comment]
@davidebbo Thank you for quick help with the issue!

Just a couple of small side-notes here:
1) It would be nice if log said something about the reason of "website shutting down" (e.g. memory consumption > X Gb);
2) Also, it would make sense if these limits were published somewhere, so developers could make appropriate choice of App Service Plan.

**Comment by dmytro-gokun** [comment]
Well ... changing to Medium Worker did not help... I would say it made thing worse. Now what i see in logs it this:

[08/07/2017 05:57:17 > f4c296: SYS INFO] Status changed to Starting
[08/07/2017 05:57:17 > f4c296: SYS INFO] WebJob singleton setting is False
[08/07/2017 05:57:21 > f4c296: SYS INFO] Run script 'Processor.exe' with script host - 'WindowsScriptHost'
[08/07/2017 05:57:21 > f4c296: SYS INFO] Status changed to Running

So, it looks like the job is killed silently. Any ideas why?

**Comment by davidebbo** [comment]
I think the problem is that processor.exe is leaking memory, so it will fill up any size VM and blow up eventually.

e.g. looking at 2017-08-07 06:04:27, I see it taking 2,734 MB of working set, so far more than we were seeing before on the small VM.

Can you check whether it leaks memory when you run it locally as well? That will make it easier to debug. And if it doesn't, you should be able to download a memory dump from Azure that you can analyze locally for leaks.

And yes, I agree that the reporting of this condition is not adequate.

**Comment by dmytro-gokun** [comment]
Actually, it does not. But it consumes a lot. When I run it locally, the peak is about 12Gb.
I know it's a lot, but I cannot make this smaller - that is what NPOI library consuming when parsing a big XLS file. 

I see two problems here:
1) Lack of proper logs/diagnostic. The job is killed silently.
2) What is it killed at all? Yes, it consumes a lot of memory, but that's why gods created virtual memory and page files :).

**Comment by davidebbo** [comment]
Let me get more info about exactly how the shutdown decision is made. Note that this is core App Service platform behavior, and not logic specific to Kudu (which just runs in user space on top of it). So I need to discuss with platform expert to better understand this.

**Comment by dmytro-gokun** [comment]
@davidebbo Do you have any update? Thing is that we are decided on the app's deployment and want to choose between WebJobs & Cloud Service Worker Roles. WebJobs look easier to manage and scale, but this issue makes it all to stay on the shaky ground...

NB. In general, would you recommend using WebJobs instead of Worker Roles in case like this?

**Comment by SainiAshish** [comment]
We are having the same issue as well, Below are the logs for web job.
After that it stops processing the messaged from service bus queue
[08/15/2017 08:24:25 > b32e65: SYS INFO] Status changed to Stopping
[08/15/2017 08:24:26 > b32e65: SYS INFO] Status changed to Success
[08/15/2017 08:24:26 > b32e65: SYS INFO] Status changed to Stopped
[08/15/2017 09:25:27 > b66915: SYS INFO] WebJob is stopping due to website shutting down
[08/15/2017 09:25:27 > b66915: SYS INFO] Status changed to Stopping
[08/15/2017 09:25:28 > b66915: SYS INFO] Status changed to Success
[08/15/2017 09:25:28 > b66915: SYS INFO] Status changed to Stopped
[08/15/2017 13:31:08 > 0511c6: SYS INFO] WebJob is still running
[08/16/2017 01:31:09 > 0511c6: SYS INFO] WebJob is still running

**Comment by davidebbo** [comment]
@dmytro-gokun I didn't hear back from the dev who would know the limit, but I just pinged him again. Generally, WebJobs are fine, but they're more *managed* than what you'd get on a worker role. So you do lose some amount of control over the policy used for things like memory limits.

@SainiAshish does your WebJob also involve using high amount of memory? If not, then you are likely not seeing the same issue (even if logs look similar).

**Comment by SainiAshish** [comment]
@davidebbo  Yes, It is a parser web job which parses the Xlsx files and save the data to Azure DB. 
On Azure i can see the high memory usage around 1.2 GB. Even I tried to see if is there any memory leak in the webjob but i could't. On local it consumes around 250mb. 
Our web job is in S2 tier.

**Comment by davidebbo** [comment]
@SainiAshish it does sound like the same issue then.

There are really two questions:

1. Is the memory usage you see in Azure normal?
2. What is the limit that App Service enforces before it starts shutting down processes?

I'm hoping to get back an answer for (2).

**Comment by SainiAshish** [comment]
@davidebbo  No it doesn't seem normal to me. On local it doesn't consume that much memory. 
We are using below package for logging in application insights 
Microsoft.Azure.WebJobs.Logging.ApplicationInsights
https://github.com/Azure/azure-webjobs-sdk/wiki/Application-Insights-Integration
Because the package still in beta version. Can it be a reason for high memory usage and the above issue.

**Comment by davidebbo** [comment]
@SainiAshish I can't easily comment on whether the memory usage observed in your process is normal or not, and whether the AI package could be at fault. Getting a memory dump might help find the source of the leak, if any.

**Comment by davidebbo** [comment]
Here is the response I got from the team:

> If the free RAM on the machine is less than 3% of the machine’s total RAM, we shut down enough worker processes to free up at least 3% of the RAM. We pick the most idle worker process to shut down. Idleness of a worker process is determined based on when the worker process last served an HTTP request.

So a lot of it depends on what other apps are running on the App Service Plan. But even if there is just one, if it uses too much memory, it will get shut off.

@dmytro-gokun your point about virtual memory is certainly valid. I'm just describing the system as it exists today.

**Comment by davidebbo** [comment]
More info: the commit limit is the following:

- Small: 4 GB (RAM is 1.75 GB)
- Medium: 7 GB (RAM is 3.50 GB)
- Large: 14 GB (RAM is 7 GB)

So it is definitely allowing some amount of paging beyond the physical memory, but stops it before it gets into major thrashing territory.

@dmytro-gokun You will need to use a Large if you need to use as much as 12 GB.

**Comment by dmytro-gokun** [comment]
@davidebbo Thank you for your investigation! I think this information is enough for us to make our choices. The only thing that I could wish here is if the logging were better (any chance to ask ask the team to work on that?).

**Comment by SainiAshish** [comment]
@davidebbo On Azure it consumes lot of memory and cpu.
![image](https://user-images.githubusercontent.com/8440148/29418561-4c346c6c-838a-11e7-8faf-3c56ccbd9a67.png)

But on local it never goes beyond  400mb.
![image](https://user-images.githubusercontent.com/8440148/29418660-988a752a-838a-11e7-8a32-571419634480.png)

So, There is no memory leak in the application.

**Comment by davidebbo** [comment]
@SainiAshish I can't explain why it would take that much more memory. My guess is that it is hitting some kind of degenerate condition on Azure causing it to go crazy. Analyzing a dump should help you figure out what the problem is.

**Comment by keggster101020** [comment]
Hi,

I'm experiencing the same issue where a continuous, always on, webjob is restarting a handful of times every hour at random hour intervals. 

>[07/17/2019 02:54:16 > 8e7cde: INFO] Job host started
[07/17/2019 02:59:07 > a0a3f4: SYS INFO] WebJob is stopping due to website shutting down
[07/17/2019 02:59:07 > 8e7cde: SYS INFO] WebJob is stopping due to website shutting down
[07/17/2019 02:59:07 > a0a3f4: SYS INFO] Status changed to Stopping
[07/17/2019 02:59:07 > 8e7cde: SYS INFO] Status changed to Stopping
[07/17/2019 02:59:07 > 8e7cde: INFO] Job host stopped
[07/17/2019 02:59:07 > a0a3f4: INFO] Job host stopped

Monitoring at the app service level shows that CPU and Memory pressure are not an issue (as previously suggested in this thread)

- Memory (max): 25% 
- CPU (max): 50% 


I have logging around capturing the shutdown events from the webjob (using the shutdown listener for c#). And aggregating that data gives the following

- Shutdown events per day: ~12
- Shutdown events per 12h:  ~8
- Shutdown events per 1h: ~6
- Shutdown events per 10m: ~4
