### ISSUE TITLE
[App Service / GO] Set GOROOT with latest version of go

### ISSUE THREAD

**Issue by iman75** [projectkudu/kudu#2560]
We are running a go app on an azure app service. 
How said on the issue #1921,  "Kudu only temporary define GOROOT and Go workspace in deployment time in order to build Go webapp". 
So during the execution, GOROOT is not defined and we need it in order to access to the file zoneinfo.zip located in GOROOT\lib\time\zoneinfo.zip.

We added GOROOT in application settings. Currently GOROOT = D:\Program Files\go\**1.7**.
However, this will not work when go 1.8 will be available.

So my question is : how to properly define a GOROOT based on the last go version?

**Comment by davidebbo** [comment]
Note that we are looking at deprecating the pre-installed golang runtime, due to very low usage. You will still be able to run a Go app by deploying the already compiled app (which doesn't require anything from D:\Program Files\go). As an alternative if you want to build via Kudu, you can copy your own go runtime to your site, which will let you drive which version you are using without affecting GOROOT.
