### ISSUE TITLE
During deployment execute command in container

### ISSUE THREAD

**Issue by jaraco** [projectkudu/kudu#2564]
Using Azure App for Containers, and following the [guide on custom deployment](https://github.com/projectkudu/kudu/wiki/Custom-Deployment-Script), I'm seeking to provide a step that installs Python dependencies for the app.

However, at the stage where deploy.sh runs, the script is in the context of the kudu container and not the app container, so doesn't have access to the necessary runtime to install the dependencies.

In the `deploy.sh` script, I tried invoking the command under Docker thus:

```
# 2. Install dependencies
docker run -v $DEPLOYMENT_TARGET:/app -t $DOCKER_CUSTOM_IMAGE_NAME pip install --upgrade -t /app/libs /app/requirements.txt
```

But that command fails because docker isn't available.

Is there a recommended way to invoke commands in the context of a custom container during deployment?

**Comment by jaraco** [comment]
I should note that I'm aware that I could install the dependencies into the container itself, but I'm seeking to avoid the step of building a new custom container on every push. These dependencies really are specific to my app (and not the container) and the workflow I'm seeking to achieve parallels the supported node model (where dependencies are installed as a deployment step and do not require a custom-built container).

**Comment by jaraco** [comment]
One possible solution might be to provide a custom container for the kudu process, and in it provide the necessary runtime environment to install dependencies. Is that an option?

**Comment by davidebbo** [comment]
@nickwalkmsft can best answer this.

**Comment by nickwalkmsft** [comment]
Hey @jaraco,

To answer your initial question - yes, there is a way to execute commands in the site container from Kudu, but it is not well exposed or documented _yet_. There are future plans to expose this in a more usable way, and we are actually looking at how best to support running deployment scripts in the app container. You may be able to make use of it now, though. This isn't really supported at this time (in that it's not documented) and I admittedly haven't tried it on my own, but it should work.

At runtime, Kudu and your app container are joined by a private network that allows an SSH connection from one to the other on port 2222. This is how we support the webssh terminal in Kudu on Linux: see [here](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ssh-support). The instructions for enabling this connectivity for a custom container are on that page too; you'll need to follow them for your custom container.

You should be able to use the SSH connectivity to run arbitrary commands in your app container from scripts running in Kudu. You could use something like [sshpass](https://linux.die.net/man/1/sshpass) or [expect](https://linux.die.net/man/1/expect) to use ssh from a noninteractive script, but you'll need to install those to /home or on-demand in Kudu since I don't think they're there right now. The biggest piece is knowing the hostname: The internal IP address of the app container is in the file /home/site/ipaddr_x, where x is the value of the WEBSITE_ROLE_INSTANCE_ID environment variable.

Caveats and other thoughts:
- If your plan is to install dependencies into the container filesystem as part of a deployment, this isn't a good idea. Unless you are putting stuff somewhere in /home, which is where your persistent site volume is mounted, anything you install is both ephemeral and only present on the individual scale unit that your script is run on. Your app containers are liable to be destroyed and restarted at any time (environment change, platform upgrade, worker migration, user-requested restart, etc.), which resets the state of the container filesystem. Dependencies should either be installed somewhere in /home for persistence, installed by your app at container startup (obviously not a good option if you have tons to install), or baked into a custom container.
- The Kudu container is not customizable and we don't have plans for this. Instead we are going to pursue running of commands in the app container via ssh. This will shift responsibility for maintaining deployment-time tools to the app container.
- FYI, running `docker` commands on App Service is a no-go, we currently have no plans to support this. Interactions with the service are limited to in-container.

If you try this, let me know how it goes.

**Comment by justinmchase** [comment]
@jaraco Its completely normal to make a container that has app specific additions to a base container. I would definitely consider just doing that.

**Comment by jaraco** [comment]
> Its completely normal to make a container that has app specific additions to a base container.

I'm trying to avoid this approach because it adds an additional step and delay and infrastructure requirement to the deployment process. I'd like for the container to be relatively static and for deployments to be lightweight. If it's necessary to have a multi-phase deployment, it requires an image to be built, tagged, and uploaded before the code can be deployed... and that additional requirement must either be done for every deployment or for select deployments based on some subset of changes.

But Node apps don't have this requirement - they can update the app and its dependencies and they'll be updated during deployment all within the single canonical Azure container. And that's the workflow I'm seeking.

> anything you install is both ephemeral and only present on the individual scale unit that your script is run on

Indeed, I'm installing the libraries to /home, so they should be shared across instances.

----

So now I'm at the stage of building a custom image with SSH installed. I've [left a comment in the page on ssh support](https://docs.microsoft.com/en-us/azure/app-service/containers/app-service-linux-ssh-support) that might help others improve that guide.

But I think I've run into a more fundamental problem with the order of operations:

- For Kudu to run commands using SSH during deployment, the container must be running.
- For the container to run, the app must also be started.

Thus, the app must be started before kudu can run deployment commands. This seems contrary to my understanding of a kudu deployment, which I would expect to run prior to starting the app.

Can you clarify: When is the container started (before deploy.sh, after deploy.sh, or both)?

**Comment by nickwalkmsft** [comment]
Hi @jaraco - First, we will definitely take your feedback on the SSH doc page, so thanks for that.

Regarding the app container startup - The short answer to your question is that the lifetime of the app container is actually not connected in any way to Kudu or a running deployment. Your app is started when it receives a request. Deployments and virtually all other Kudu actions, with the obvious exception of SSH, are able to operate independently of the app container via the shared persistent filesystem.

There's currently no supported way to request an app startup directly from Kudu in the way that's needed here. You could make a request to your site's public URL and wait for a response, but if you're scaled across instances, there's no guarantee that it will actually happen on the same instance.

There's also no guarantee your environment is in a state where your app container will start up and remain running. Not only does the container need to not exit, it has to respond to an arbitrary HTTP request on the bound port before we allow incoming requests from the Internet, and we will terminate it within a certain timeout if it doesn't. So if your environment is in a state where this doesn't happen, you might be able to get an SSH request to your app container from Kudu if it was able to start the SSH server, but there's no guarantee how long it's going to remain running unless you confirmed that it served a response to the pinger.

For all these reasons, this needs actual platform support, and we are looking into how best to do it. I'm not sure we will ever be able to give more than "best effort" support to running in the actual app container instance since we don't have control over whether it will remain running, but we are looking at other options as well.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by jaraco** [comment]
Thanks for following up. I've since sold the product that was reliant on this design. If I'm ever tempted to use Azure again, I'll be cautious about it due to this limitation (which may or may not exist today).
