### ISSUE TITLE
Zip deployment slow because of processing

### ISSUE THREAD

**Issue by nphmuller** [projectkudu/kudu#2602]
My node.js application consists of a lot of files (about 15.000). This means that normal deployments are pretty slow (about 7-10 minutes) because all these files get compared and updated.

I tried the zip deployment preview, because I was hoping this would solve my slow deployment problem. However, after looking at the log from the zip deploy, I noticed that after unpacking the zip file (which is very fast), there is a processing step in which all files get processed (not sure what this processing is, I think the already deployed files get compared to the files from the zip deployment?). This processing step however slows everything down, to the speed of the old deployment.

I was hoping there was or will be a way of turning of this processing step and simply 'blindly' moving all files from the zip to the destination.

**Comment by davidebbo** [comment]
@nickwalkmsft is the expert here.

Though I would think that blindly copying everything would be even slower, unless it so happens that the majority of files have in fact changed (not common for incremental deployments).

**Comment by nphmuller** [comment]
@davidebbo If I read the log correctly the zip was already unpacked, so moving the unpacked files shouldn't take that long, right?

Maybe the solution is in properly implementing incremental deployments for me? Because the entire project is rebuild before deployments, timestamps have changed. So the deployment engine thinks all files have changed.

**Comment by nickwalkmsft** [comment]
> properly implementing incremental deployments

The root of the problem is simply the fact that a 15,000-count file operation onto the site volume is going to be slow.

The way this works in all Kudu deployments is KuduSync uses DirectoryInfo.GetFiles() to load all of the file metadata for the source and the target into memory at once in an efficient way; we don't read any of the content. Then we compare timestamps to copy as few files as possible. Comparing every file by content would require a full read of each target file, which I don't think is going improve performance when you're dealing with lots of small files, at least not in the current implementation of KuduSync, which is not multithreaded.

Have you tried using the [zip API](https://github.com/projectkudu/kudu/wiki/REST-API#zip), maybe not for production usage but just to compare performance? You don't get deployment semantics but it completely skips everything but the unzip, overwriting files where necessary (and ignoring leftover files), so you won't be able to get anything faster than that.

**Comment by nphmuller** [comment]
Yeah, I meant that I should implement a build-system that didn't rebuild any unmodified files, keeping the timestamp unchanged. I definitely agree that only comparing the timestamp is better than hashing the files and comparing the hash.. That would be way slower.

Tried the zip API, but it also takes a while. Guess it's a good reason to get rid of our huge legacy app and speed up the development of the new version (with way less files).

Thanks for the help!
