### ISSUE TITLE
Continous WebJob restarts with "Always On" set in portal

### ISSUE THREAD

**Issue by pabloarista** [projectkudu/kudu#2617]
In our AppService we have 2 continuous web jobs running. The AppService has the "Always On" set to "On". Even with this setup, WebJobs restart under 2 different cases

Case 1 is when the website is shutting down, but no-one has shut it down or restarted it:

`[11/08/2017 12:38:19 > 63fceb: SYS INFO] WebJob is stopping due to website shutting down
[11/08/2017 12:38:19 > 63fceb: SYS INFO] Status changed to Stopping
[11/08/2017 12:38:24 > 63fceb: SYS INFO] WebJob process was aborted
[11/08/2017 12:38:24 > 63fceb: SYS INFO] Status changed to Stopped
[11/08/2017 12:38:24 > 63fceb: SYS INFO] WebJob singleton lock is released
[11/08/2017 12:38:54 > 63fceb: SYS INFO] Status changed to Starting
[11/08/2017 12:38:54 > 63fceb: SYS INFO] WebJob singleton setting is True
[11/08/2017 12:38:55 > 63fceb: SYS INFO] WebJob singleton lock is acquired
[11/08/2017 12:39:10 > 63fceb: SYS INFO] Run script 'run.cmd' with script host - 'WindowsScriptHost'
[11/08/2017 12:39:10 > 63fceb: SYS INFO] Status changed to Running`

Case 2 is when the WebJobs files have changed, but no-one has touched any of the files in the folder or even in the temp folder where it's running:
`[10/28/2017 21:51:13 > de8f96: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[10/28/2017 21:51:13 > de8f96: SYS INFO] Status changed to Stopping
[10/28/2017 21:51:18 > de8f96: ERR ] Thread was being aborted.
[10/28/2017 21:51:18 > de8f96: SYS INFO] WebJob process was aborted
[10/28/2017 21:51:18 > de8f96: SYS INFO] Status changed to Stopped
[10/28/2017 21:51:18 > de8f96: SYS INFO] WebJob singleton lock is released
[10/28/2017 21:51:18 > de8f96: SYS INFO] Status changed to Starting
[10/28/2017 21:51:18 > de8f96: SYS INFO] WebJob singleton lock is acquired
[10/28/2017 21:51:18 > de8f96: SYS INFO] Run script 'run.cmd' with script host - 'WindowsScriptHost'
[10/28/2017 21:51:18 > de8f96: SYS INFO] Status changed to Running`

We contacted Support and got nowhere. Support says that a change in the portal settings would make this happen (Seems like they didn't consider the 2 different cases). Support said in their logs someone had changed the settings in the portal, but we don't see it in our activity log and even when inspecting the files we don't see what the change was. Support says they have no way to getting us more details, but that log entry is lacking when we search for it. We have no entry of anyone changing the settings.

These are .NET Core WebJobs by the way. I don't know if it's a bug with .NET Core. There have been some times where we have changed the files, but normally we shut it down before that happens. Sometimes we have restarted the AppService, but not every time the log shows these entries. We don't have an app.config, so I'm not sure if that's even relevant. Most posts are not about .NET Core, so it's hard to find anybody with a similar situation.

One thing we thought it was at first was the auto-publish when doing a git-merge, but the times don't match at all, we're talking about sometimes hours and even days differences in publishing when the WebJob(s) restart.

Please, what do you need from us? We can send an email with credentials to get on our account if needed or do you just need our config files? It's such a special case that I'm not sure what information is relevant. This has been on-going for over a month now and it's just a big hurdle. We started talking to the Google Cloud Platform team to see what options they have for us, but if we can find a solution here we would prefer not to migrate.

**Comment by pabloarista** [comment]
Anybody at all? We really love Azure, but this bug (or whatever it is) is not a real hit with us. CS is useless. We would love to avoid switching over to Google, but we have started our talks with Google and are looking to setup a migration plan. Would definitely love to avoid all of that, but we need some help guidance on this bug.

**Comment by watashiSHUN** [comment]
can you share your Web App name, directly or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly), so we can take a look

**Comment by davidebbo** [comment]
Make sure you provide all times as UTC. Also, please include the support case number for full context.

**Comment by pabloarista** [comment]
The case number is 117100716459158.

I created a dummy site: dummy-app-ra

The 2 affected sites are:
1) ends with l
2) starts with w

I can give you the dates of when we detected originally, but this has been happening every other day, if not every day.

10/25/2017 23:38:04 
10/25/2017 02:00:02

We appreciate the help. If anything I missed, let me know and so I can provide.

**Comment by davidebbo** [comment]
@pabloarista some of the logs only go back one month, so that is a little too old. Can you provide a more recent time for the site that starts with 'w' (the one in the support case), and please make sure the time is UTC.

**Comment by davidebbo** [comment]
@pabloarista looking at the support case, it looks like it was closed just a couple days ago, as the support engineer was not getting a response from you. Did you see the latest mails that they had sent? I'd like to avoid redoing all the investigation here is they already have an ongoing investigation there.

**Comment by pabloarista** [comment]
Sorry, I didn't respond earlier. Yes the last thing CS said was to add to settings.job:

`"is_in_place": true`

This isn't a solution, all it's doing is not moving the assemblies to a temp folder. But yes CS did close out the ticket after this. Had some urgent matters that was unable to focus on that, life of working in a start up.  I do have some newer dates for you:

`12/05/2017 17:14:30 Detected WebJob file/s were updated, refreshing WebJob
12/01/2017 19:12:19 WebJob is stopping due to website shutting down`

Any ideas?

**Comment by tanvirhussaindca** [comment]
Hi @davidebbo we have the same issue above but it don't tell us which files were updated. Any guidance would be great.

**Comment by tuthan** [comment]
I also have the same behavior. while we didn't have any update to the app, webjobs just restart magically by itself.

[12/13/2018 23:08:55 > 7ae254: SYS INFO] WebJob is still running
[12/13/2018 23:09:00 > 66803a: SYS INFO] WebJob is still running
[12/14/2018 05:45:14 > 7ae254: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[12/14/2018 05:45:14 > 7ae254: SYS INFO] Status changed to Stopping
[12/14/2018 05:45:15 > 66803a: SYS INFO] Detected WebJob file/s were updated, refreshing WebJob
[12/14/2018 05:45:15 > 66803a: SYS INFO] Status changed to Stopping
[12/14/2018 05:45:15 > 7ae254: SYS INFO] Status changed to Success
[12/14/2018 05:45:15 > 7ae254: SYS INFO] Status changed to Stopped
[12/14/2018 05:45:15 > 7ae254: SYS INFO] Status changed to Starting

**Comment by suwatch** [comment]
This can happen due Azure AppService upgrade where we have to switch out a file server for maintenance.   As a result, continuous webjob may be restarted.

**Comment by pabloarista** [comment]
That would be insane if this is an ongoing thing every day because that’s what’s happening to us still now we’ll over a year. We modified all of our webjobs and stored procedures to just continue when this happens, because if not imagine we can lose over an hours worth of processing. We’re actually in talks with Google on migrating. There are a lot of good things with Azure, but also a lot of nuisances like this. I mean this is one of many explanations that I’ve heard from Microsoft. Doesn’t give us confidence in the service.

**Comment by koverda** [comment]
how were you able to get these logs?

**Comment by pabloarista** [comment]
@koverda you can go to https://appName.scm.azurewebsites.net/azurejobs/#/jobs

where appName is the name of your app service.

For us it stopped happening so often. We read buried on the interwebs somewhere that it could be related to the system resources. so we moved one of the offending webjobs to an isolated appService. still happens on occasion, but a lot less. This may not be a solution for everyone. Crazy thing is now we actually do need for it to restart automatically. the way it was doing previously on 1 webjob and that one completely stopped lol.

we've had such a bad experience with the webjobs (and Azure overall). we had to move 1 process to a VM and now there may be 1 other process (1 particular data calculation is what I mean by process) to that same VM because it has some real weird behavior.

We're not very happy with Azure. We started the migration to the Google Cloud Platform. We had a lot of meetings with them and explained this to them. They are on board and guarantee that these types of problems won't happen and have dedicated resources to help us to ensure if and when it does happen, to get it fixed fast. To date we still have no real response from MS Azure CS on the detailed error messages. the logs that are on the kudo site are very generic messages without the details.

**Comment by koverda** [comment]
Ah yep i'm familiar with that, unfortunately my job processes thousands of messages per minute, so going back in the logs is troublesome.

**Comment by pabloarista** [comment]
@koverda you can also go https://appName.scm.azurewebsites.net/ and go in either in the console or powershell and I believe it's the root/data/logs/jobs/ somewhere there, and you can download the logs. if you do get a lot of logs, Azure doesn't always clear these you have to clear them yourself. We've ran into this issue before. you can also download the publishing profile from the appService summary view. there you can ftps (or ftp if you're feeling adventurous lol) to the server and go to the same location and just download all of the logs in one shot. it would be easier to do a search. you can open up the folder on say VS Code and then search. could be much faster.

**Comment by pmeems** [comment]
Anybody got a solution for this? We have a .NET v4.7 webjob which runs for months (20+) without any problem but the last 3 weeks when it is processing a large file which takes about 45minutes it shuts dows the website(!) and thus restarts the webjob. This happened before once in a while, so I've implemented a lot of code to handle this and to make sure the process is starting again when the webjob comes alive again, I'm using a Queue triggered webjob. Last night the large file was processed again. No errors where logged, only this:
`[11/20/2019 17:31:26 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/20/2019 17:31:26 > b5cf2c: SYS INFO] Status changed to Stopping`
`[11/20/2019 17:31:31 > b5cf2c: SYS INFO] WebJob process was aborted`
`[11/20/2019 17:31:31 > b5cf2c: SYS INFO] Status changed to Stopped`
`[11/20/2019 17:31:50 > b5cf2c: SYS INFO] Status changed to Starting`
`[11/20/2019 17:31:50 > b5cf2c: SYS INFO] WebJob singleton setting is False`

and several times later that night again:
`[11/20/2019 17:31:26 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/20/2019 18:42:14 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/20/2019 21:17:21 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/20/2019 21:36:51 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/20/2019 21:58:11 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/20/2019 22:17:34 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/21/2019 03:13:41 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`
`[11/21/2019 03:36:21 > b5cf2c: SYS INFO] WebJob is stopping due to website shutting down`

Processing the large file started at:
`[11/20/2019 16:46:30 > b5cf2c: INFO] Start processing 5436`
and again at:
`[11/20/2019 17:41:42 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 18:03:35 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 18:52:14 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 19:17:10 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 19:48:55 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 21:29:10 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 21:44:34 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 22:08:20 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 22:27:40 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 22:46:04 > b5cf2c: INFO] Start processing 5436`
`[11/20/2019 23:38:56 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 00:45:45 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 01:06:35 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 01:37:52 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 01:55:18 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 02:27:54 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 03:06:05 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 03:46:49 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 04:03:57 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 04:49:05 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 05:12:18 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 05:28:41 > b5cf2c: INFO] Start processing 5436`
`[11/21/2019 07:01:30 > b5cf2c: INFO] Start processing 5436`

During the evening other (smaller) files do get processed due to
`config.Queues.BatchSize = 8`
At night the large file is the only file that is processed.

I'm now running the webjob locally in VS 2017 and no errors are reported and it finished as expected in 37 min.
The webjob is parsing a previously uploaded Excel-file and saves the data in a SQL Server table.
Smaller files (= less data) are no problem. Previously we had no problems with these large files.
Did Microsoft change some settings again in Azure which we need to adjust? I did notice the GUI of Azure Portal was also changes around 3 weeks ago. 
We had to make changes previously to other parts of our application because of the sudden changes made by Microsoft.

**Comment by pabloarista** [comment]
@pmeems you said this has gone on for months without problems, but how big is the file? was always the same size? is there a lot of memory/CPU being used? I would assume that there were also no code changes in how the file is handled. I found out that when there are too many resources, it just restarts. doesn't tell you why, but you have access to that data too. you can confirm what it's using. if you have several webjobs and app services in the same app service plan, that happens. happened to us.

**Comment by pmeems** [comment]
The file is between 115-125 MB. The most memory is used when saving the data to the database. When running locally in debug mode I can see the CPU goes up to 100%, but I have 8 cores and my other programs stay responsive.
I also thought about too many resources. That might be possible during the evening, but during the night it is the only process that is running. No other web jobs, no other files.
We already run an S2 website.
Can I somehow see what the reason for the restart is? If it is too many resources we could temporarily increase our website to an S3 just before parsing this large file. This specific file is only uploaded once a week.

**Comment by suwatch** [comment]
@pmeems  Please provide a webapp name here or [indirectly](https://github.com/projectkudu/kudu/wiki/Reporting-your-site-name-without-posting-it-publicly) (my apology if it was in your explanation somewhere already) as well as a webjob name.    It is also useful to look up the information from https://docs.microsoft.com/en-us/azure/app-service/overview-diagnostics.

**Comment by pmeems** [comment]
Thanks @suwatch for your assistance.
Our subscription is `20583...634867` 
The app service it the one ending with `2` and then the `-prod` slot.
The Webjob is ending with `-WeeklyImports`
The date is the night of 20 nov - 21 nov.

In the diagnostics I do see this:

-  _MyWebApp_[Kudu] is consuming an average of 61.29% of Physical Memory on instances consuming high Memory
- _MyWebApp_[Kudu] has High CPU: 72.19%

Not sure what to do next.

**Comment by pmeems** [comment]
Today it is happening again. The webjob restarts every 25-30 minutes. Around the time the file is processed and is saved using EF6.
So `ProActive Auto-Healing` wasn't the problem.

How can I tell Azure not to restart my webjob when it is a bit busy. 
Or can we tell Azure not to give all available memory to our webjob, but just 60%?
We don't care it takes a bit longer if it can't allocate all the available memory.

I'm now running the webjob locally inside VS. And after 25 min. my fans are starting to blow, so it must be working hard. But my progress manager says it is just using around 55% of my CPU and a stable 53% (8.8GB) of my memory.

**Comment by suwatch** [comment]
You are using S2 plan with 3.5 GB memory.   At 2019-11-27 10:37 UTC, SubAdvies.WeeklyImportsJob.exe job spiked to commit from 500MB to 5GB of memory for a sustaining period of time!   This caused the process to be unstable and shutdown.    If this is by design for your webjob to consume such, consider switch to S3 (7GB) plan instead.

**Comment by pmeems** [comment]
I know the default answer of Microsoft for almost every issue is to upgrade to a more expensive plan, but we are already paying $$$$ for a small webapp (we also use PowerBI and ElasticPool).
I don't understand why Azure is shutting down my webjob when it finally has some work to do. Most of the time it is running on less than 10%, with some occasional spikes to 60% for about 5-10 minutes and once a week it needs all resources for about 30 minutes and this is not allowed.

Can I not tell Azure to leave my webjob to do its work and don't restart? Perhaps using a per session variable? Or can I limit my webjob to not consume more than 80%?

**Comment by pmeems** [comment]
As @suwatch suggested it seems to be a resource issue. I've now created a tool that is splitting my large Excel sheet in multiple smaller versions and those smaller files are processed fine.
So, for now, it solves my problem. 
But I still think the webjob should not restart on its own or at least log it somewhere why it is restarting.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by pabloarista** [comment]
the company switched to GCP a few years ago. I do consultant work for them so whenever I have to go on the backend I do see that this isn't an issue with GCP. I would hope by now Azure has fixed all of these issues, but I have no way to confirm any of it as the only work I do for Azure now is just an iOS app I created that deals with Azure Storage Tables.
