### ISSUE TITLE
git in Kudu Powershell fails with "Window title cannot be longer than 1023 characters"

### ISSUE THREAD

**Issue by dstj** [projectkudu/kudu#2635]
Opening a Powershell Console on Azure and running `git --version` twice, the second run fails with "Window title cannot be longer than 1023 characters" as error message. All subsequent runs also fail.

This seems to only happen on a "preprod" deployment slot. The main slot is not affected by this.

The same behavior was observed on two different Azure Website, on two distinct AppService plans.

Here's a complete output of my session:

```
Kudu Remote Execution Console
Type 'exit' then hit 'enter' to get a new powershell process.
Type 'cls' to clear the console

PS D:\home> git --version
git version 2.14.1.windows.1
PS D:\home> git --version
git version 2.14.1.windows.1
Window title cannot be longer than 1023 characters.
PS D:\home> At line:1 char:1
+ git --version
+ ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [], RuntimeException
    + FullyQualifiedErrorId : Argument
```

This makes all attempts to run powershell scripts unreliable.

Thanks.

**Comment by christianrondeau** [comment]
It also looks like piping the output of a git command to a file using out-file actually writes `Window title cannot be longer than 1023 characters` to the file...

**Comment by davidebbo** [comment]
Strange, it seems to happen sort of randomly. Not at all on some apps, always on others, and on and off on others. And only with the Powershell console. Might be some issue at the sandbox level rather than Kudu proper.

**Comment by christianrondeau** [comment]
That's what we have seen in #2048 (though this specific GitHub issue is not focused on this specific error), but why it happens exactly is not clear.

Looking at the source code (we can print the stacktrace if we use `trap` and print `$_.Exception`) it looks like the original "fake" console window title might be more than 1023 characters in the first place, so when the script finishes and the original title is brought back, it crashes. But when we set `$host.UI.RawUI.WindowTitle = 'Mediaclip Library Update Tool'` and then print `$host.UI.RawUI.WindowTitle`, we see the title has just been dropped.

At this point, we'll need to rewrite all of our scripts in `.bat`, which is really, really not cool. Otherwise, our PowerShell scripts work fine.

Note that the "real" use case that breaks for us is a script that simply runs a series of `git` commands, nothing fancy otherwise.

**Comment by aaronamm** [comment]
This problem is still happen to me.
I think PowerShell should be main script for Kudy.
PowerShell is powerful and easier to maintain than .bat.

I have trying to fix it by adding
```
$host.UI.RawUI.WindowTitle = "Windows PowerShell"
```

However, the problem still occur sometimes.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
