### ISSUE TITLE
Trigger container service deployment

### ISSUE THREAD

**Issue by marcel-devdude** [projectkudu/kudu#2651]
Hey guys,

i have a web container service on azure and would like to trigger a deployment in our CI tool with a webhook.

I found the [Manually triggering a deployment](https://github.com/projectkudu/kudu/wiki/Manually-triggering-a-deployment) guide. But this didn't work for container services (I guess?).

I also tried to trigger the deployment with this webhook:

```
POST https://$username:password@foo.scm.azurewebsites.net/docker/hook
```

This works (if the `DOCKER_ENABLE_CI=true` is set), but during the deployment no new docker image is pulled:

```
2017-12-15 15:59:24.575 INFO  - Issuing docker pull foo.azurecr.io/bar/baz:latest
2017-12-15 15:59:25.046 INFO  - docker pull returned STDOUT>> latest: Pulling from bar/baz
Digest: sha256:a30a064d660c8834206c7e1438f7270a9a4efa03ec571566e91d80f1df29ec6e
Status: Image is up to date for foo.azurecr.io/bar/baz:latest
```

Is it possible to trigger a new deployment with a webhook? Or how about the right way to trigger a deployment from an external CI tool?

Many thanks!

**Comment by nickwalkmsft** [comment]
Hi @marcel-devdude,

It sounds like you've pushed a new container image and you want to get it running in your app, is that correct?

The deployment guide you linked is for deploying apps from source code via git or other SCM providers, that won't help here.

An app running a custom container will check the source repo for a changed image every time it starts up. The webhook that you mentioned simply triggers a restart of the app container, so that this check is run and a new image is loaded if one is available.

The message you got is "Image is up to date." Are you sure you pushed a new image to the same repo _and_ tag? Your app is configured to run with only the image name you give it, it will not check for new/different tags.

**Comment by marcel-devdude** [comment]
Ah, ok. I thought the service will pick the last pushed Image. With the same tag it works. 

But only with DOCKER_ENABLE_CI=true this feels a bit „hacky“. What is the „professional“ way to handle new deployments?

**Comment by nickwalkmsft** [comment]
That setting isn't a hack at all, it's a "safety switch" that can be easily turned off if you want your app to stop reacting to webhooks you may have forgotten about or can't figure out how to turn off. Although you could always reset your publishing profile password instead.

The webhook is a first-class solution, but one could argue that the full-blast "professional" way of managing images and deployments is the following:

- Disable the webhook.
- Use a build/CI service like VSTS to build and push your Docker image in an automated way. Since your image powers a live site, your build process should manage your tags similar to build IDs: always push to a new tag with a unique identifier for traceability, keep old builds around for rollback/investigative purposes, and maybe publish to multiple tags for ease of use (like "latest", but configure your app with that).
- Once the image is pushed, use the build service to push new configuration to your app via ARM to change the tag. This will trigger a restart and your new image will be pulled and run.

**Comment by marcel-devdude** [comment]
Thank you. Very helpful. I‘ll have a look at the VSTS solution.
