### ISSUE TITLE
Make Kudu more informative about the reasons of Web App restarts

### ISSUE THREAD

**Issue by alex-zyl** [projectkudu/kudu#2656]
Our product uses continuous webjobs running on 3 instances to run long-running processing operations that may take a few days to complete.
During the last few months we observed multiple web app instances restarts. Sometimes it takes time to investigate why the next restart happened.

So far we've got the following list of possible reasons:
1. Infrastructure issues / upgrades visible from App Restart Analysis event view (easy to track)
2. Changes in App Service settings (also easy to track from Activity Log/webjob log)
3. SCM upgrades - this gives some pain
    Most of the time webjobs restart with the following message: " WebJob is stopping due to website shutting down" which explains nothing. So there were two cases:
    a. Checking C:\DWASFiles\Sites\#1SITE_NAME\Config\SiteLastTimeModificationTime.txt shows last site modification time;
    b. changes in applicationhost.config file: we've observed it once when kudu path\version had changed.
    These two cases are causing web app recycling and are not easy to track
4. ???

During last two days there were also few restarts: 
1. All instances at the same time - which can probably be explained by infra / scm upgrade;
2. Restart of a single instance 3 times a day - still no clue why;

Having better restart logging could save hours of time spent on investigating the issues. Some of them still stay unknown.

Also from my point of view scm upgrade should not be performed automatically as it causes webjob restarts. Maybe it would be better to add the setting to manually perform upgrade like it was available for Functions runtime.

**Comment by davidebbo** [comment]
There have been more restarts than usual lately due to the upgrade to 2016, as well as the security fixes related to the Intel flaw (upgrades were staged in multiple rounds). I would expect the frequency to go back to its more usual schedule once the dust settles on this event.

But generally, VM upgrades are an intrinsic part of the App Service PaaS system. Note that there is no such thing as an 'scm upgrade' per se. When a platform upgrade happens, everything that runs on the old VM needs to stop (with a small grace period), and then gets moved to a new VM (with some overlap so there is no downtime for Web Apps).

Unfortunately, that does mean that triggered WebJobs that run for multiple days are at risk of getting killed. I would say the system was probably not designed for this type of usage pattern. Or the WebJob would need to have a checkpoint system so it can resume where it left off, though that does add complexity.

Closing this issue because this is not really something Kudu/WebJobs specific, but is an intrinsic part of how App Service operates.
