### ISSUE TITLE
Consider updating Nuget packages version

### ISSUE THREAD

**Issue by pakrym** [projectkudu/kudu#2668]
As commented by @emgarten in https://github.com/emgarten/Sleet/issues/27#issuecomment-358841813:

> I'm surprised and scared to see NuGet.Data.DataClient being used still, that was the first prototype of a reader for nuget v3 feeds. It never shipped outside of a preview. I don't think this even exists on nuget.org, or if it did it was unlisted a while ago.

It also exhibits behaviors fixed in later nuget client libraries. In my case it wasn't able to read BOM prefixed feed index created by Sleet.

**Comment by watashiSHUN** [comment]
looks like kudu is using some pretty old pre-release nuget client
![image](https://user-images.githubusercontent.com/6531400/35165081-c55d5c34-fd01-11e7-912c-6c38bc8dbf98.png)

**Comment by nickwalkmsft** [comment]
I am working on Kudu on .NET Core... I noticed this and *briefly* looked at it (because it's for site extensions, which are not a priority) and I couldn't make heads or tails of which packages we'd replace them with. The "shape" of the set of packages used to interoperate with Nuget has changed significantly since those features were created.

**Comment by emgarten** [comment]
I forgot the nuget.protocol.v2v3 package made it to nuget.org, that explains a lot. And yes, Kudu was first adopter of the v3 protocol if a I recall :smile:

The only package you should need now is: `NuGet.Protocol` https://www.nuget.org/packages/NuGet.Protocol/

Here is an example of reading a feed:
https://github.com/NuGet/NuGet.Client/blob/bd56c87bcdf01dae64fe36d18cee60c7e055cfc1/test/NuGet.Core.FuncTests/NuGet.Protocol.FuncTest/FindPackageByIdResourceTests.cs#L21-L40

The older NuGet.Protocol.V2V3 was a prototype of reading the v3 feed as RDF, indexing it all into a table store/database, and then querying it. It turned out to be very complicated and slow. NuGet.Protocol now just reads the feed as json and should be much faster for you.

**Comment by nickwalkmsft** [comment]
@emgarten Thank you for the pointer!

**Comment by davidebbo** [comment]
As I recall, the history is something like that:

- We were using an official NuGet v2 client package
- A scenario came up that required us to support v3 feeds. It was neither nuget.org not siteextensions.net, but some new scenario (that later ended up not happening)
- To make this work, we worked with someone from NuGet team (John), who came up with the pre-release packages that we ended up using
- Later, I think there was some attempt to move to something newer, but we found that there was no workable replacement for what we were using (can't recall details), so we've been staying with the ancient prerelease packages.

I guess I'd say that unless something is concretely broken (doesn't appear to be the case), I'm tempted to just leave this alone.

**Comment by emgarten** [comment]
Sounds right, and I would imagine that the API shape has completely changed. If it works it works, but if you do hit perf or memory issues from NuGet.DataClient the newer protocol version should help.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
