### ISSUE TITLE
Azure Web App sandbox infos for Linux

### ISSUE THREAD

**Issue by ChristianWeyer** [projectkudu/kudu#2693]
This is an **excellent** resource for Windows-based Web Apps (and Functions, FWIW):
https://github.com/projectkudu/kudu/wiki/Azure-Web-App-sandbox

Is there a similar document outlining the details for Linux (especially for Functions)?

Thanks.

**Comment by davidebbo** [comment]
I don't know of such document. But note that there is no sandbox per se on Linux. It's just running in a standard Docker Container, and any restrictions come out of that rather than from special limitations imposed by app service (unlike on Windows, where there is a special sandbox with very specific restrictions).

@JennyLawrance may have more to say about this.

Closing since this is more of a discussion item, and not directly related to Kudu (but it can be used for continued discussion).
