### ISSUE TITLE
Error during deployment on web app (Microsoft Web Deploy is not correctly installed)

### ISSUE THREAD

**Issue by omgjust** [projectkudu/kudu#2775]
I get the following error when trying to deploy to a web app from a git repository:

`"D:\home\site\repository\WebProject\Web\Web.csproj" (default target) (1) ->
(CheckAndCleanMSDeployPackageIfNeeded target) -> 
  D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild\Microsoft\VisualStudio\v15.0\Web\Microsoft.Web.Publishing.targets(3758,5): error : Package/Publish task Microsoft.Web.Publishing.Tasks.IsCleanMSDeployPackageNeeded failed to load Web Deploy assemblies. Microsoft Web Deploy is not correctly installed on this machine. Microsoft Web Deploy v3 or higher is recommended. [D:\home\site\repository\WebProject\Web\Web.csproj]

    14 Warning(s)
    1 Error(s)

Time Elapsed 00:02:12.18
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild-15.3.409.57025\MSBuild\15.0\Bin\MSBuild.exe" "D:\home\site\repository\WebProject/Web/Web.csproj" /p:DeployOnBuild=true /p:configuration=Release /p:publishurl="D:\local\Temp\8d5c1ffefcef5cf"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\73.10510.3399\bin\Scripts\starter.cmd deploy.cmd`

When i deploy from Visual Studio 2017 everything works.

For the deployment from the repository i am using this script:  
https://github.com/projectkudu/KuduScript/blob/master/lib/templates/deploy.batch.aspnet.wap.template

**Comment by davidebbo** [comment]
Can you share the content of your `Web.csproj`? Or better yet, if you can minimize the repro, can you share a repo that demonstrates the issue, per [these instructions](https://github.com/projectkudu/kudu/wiki/Using-a-git-repo-to-report-an-issue)? Thanks!

**Comment by davidebbo** [comment]
@omgjust thanks!

/cc @watashiSHUN & @vijayrkn

**Comment by watashiSHUN** [comment]
looking at your `deploy.cmd`:
![image](https://user-images.githubusercontent.com/6531400/40636634-da0bdae8-62b4-11e8-846d-fb21b43794e9.png)
you are using the template for deploying **function app**, not web app. And different apps should be built with different msbuild arguments, I submitted a pull request as a fix: https://github.com/omgjust/AzureDeploymentExample/pull/1
I can understand this mistake since function app is the one of the few default template that uses **msbuild15** but soon you should be able to toggle msbuild version with a simple app setting: https://github.com/projectkudu/KuduScript/pull/95/commits/3bd6f7bc730bbebab7614f7ce73109c954247448

**Comment by omgjust** [comment]
Thank you for your help. It works fine with the new script.
