### ISSUE TITLE
Azure GitHub deployment | Remove additional files at destination folder.

### ISSUE THREAD

**Issue by vikguptaMS** [projectkudu/kudu#2822]
Hello Team,

When we use GitHub as a deployment option in Azure web app deployment then it first deploys content to the Repository folder and then deploys to WWWROOT which doesn’t delete the additional content available in the WWWROOT folder.
If I have any additional files under WWWROOT folder which is not the part of GitHub committed deployment then that file will not be deleted.
While in Visual Studio deployment we can “remove additional files at destination” through setting tab.

Below it the GitHub deployment cycle,
https://github.com/projectkudu/kudu/wiki/Deploying-from-GitHub
 
Is there any option available in GitHub which can delete the additional files available at the destination.

Thanks in advance!

**Comment by suwatch** [comment]
Kudu will only delete the files which are part of previous deployment but removed from current one.  See https://github.com/projectkudu/KuduSync.    Is that you observed?   I don't think we have option currently to remove anything not in current deployment.   It seems like a good option, IMO.

If you are adventurous and have time, try improving KuduSync (introduce new knob) and send us PR.   We can try to integrate and light up end-to-end.

**Comment by ppanyukov-poq** [comment]
Any update on this? It's been 2.5 years.

**Comment by reilem** [comment]
I made two deployments using the github action `azure/webapps-deploy@v2`:
1. First deployment added a src file: `DEPLOYMENT_MARKER`
2. The second deployment added a new src file `DEPLOYMENT_MARKER_1`, and removed the old `DEPLOYMENT_MARKER` file

After the second deployment I SSH into our app service files and check `/home/sites/wwwroot` and this is what I see:

<img width="1036" alt="Screenshot 2021-04-09 at 15 20 42" src="https://user-images.githubusercontent.com/11155505/114187050-dcbc7c80-9947-11eb-9a6f-7dcd13608dfd.png">

The old files are still there. This means that if you have a bug in an old file that is causing your app to crash on startup and you try to solve the problem by removing the file. The problem will persist. This one issue is basically making Azure App Service unusable in any enterprise or professional capacity.

@suwatch will this issue ever be fixed?

**Comment by suwatch** [comment]
Linux or Windows?   Assuming this is the test site - provide the sitename, utc times of both deployments.

**Comment by reilem** [comment]
This is a Linux App Service running Node 12. Is it okay if I email you the details? I am currently also in contact with microsoft support, they suggest setting this option in Kudu: `SCM_ZIPDEPLOY_DONOT_PRESERVE_FILETIME=1` is there a way to use this option with this action?

**Comment by reilem** [comment]
I was able to solve my issue by adding this to my app service configuration: `WEBSITE_RUN_FROM_PACKAGE="1"` more info can be found on it here: https://docs.microsoft.com/en-us/azure/app-service/deploy-run-package#enable-running-from-package.

Note: this works for me because our app is stateless and does not require writing to files

**Comment by paulcam206** [comment]
Just dropping a note here that this is still an issue when using zip deploy.

**Comment by richardweaver** [comment]
Trying to wake this: still an issue. WEBSITE_RUN_FROM_PACKAGE doesn't help. In fact, my only resolution has been to set it to 0 so I can use SSH to rm -rf the whole wwwroot folder and then deploy over the top, which is crazy.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by karlmacklin** [comment]
> Hi
> 
> If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure: https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
> 
> This way we can better track and assist you on this case
> 
> Thanks,
> 
> Joaquin Vano Azure App Service

I am another who suffers from this bug/design error.
How can I track this issue over at learn.microsoft.com ?

Or are you saying that every individual that is waiting for this issue to be solved should raise individual support requests, instead of something collaborative such as this issue which perfectly explains the problem?

**Comment by jvano** [comment]
Yes, please file your individual support request. This will allow us to know more information about your case like your site id, etc. This is why it's important you file you support request.

**Comment by karlmacklin** [comment]
> Yes, please file your individual support request. This will allow us to know more information about your case like your site id, etc. This is why it's important you file you support request.

I fear there might be some miscommunication in this matter.

The issue is not specific to us. Anyone who uses github actions to deploy a web app as described earlier in this issue will be affected. So a specific site id etc is 100% irrelevant.

There is no way to deploy to a "fresh" filesystem. If your app's behavior is to write new files, these files are now stuck forever.

Unless there was an option to deploy with a setting to delete all previous files (no matter if a previous deployment are responsible for them or not).

Are you 100% we still should open support tickets for this even though it is irrelevant? I don't want to accidentally end wasting anybody's time by doing so.

**Comment by jvano** [comment]
The site id was just an example of information we might need. We will need some information for us to filter the logs and find the site, region, scale unit, time ranges, etc. so please file an azure support request if you need support.

**Comment by karlmacklin** [comment]
> The site id was just an example of information we might need. We will need some information for us to filter the logs and find the site, region, scale unit, time ranges, etc. so please file an azure support request if you need support.

I do not have permission to file an azure support request according to the azure portal.
