### ISSUE TITLE
Need clarification about App service local cache behaviour and d:\home\data

### ISSUE THREAD

**Issue by christianarg** [projectkudu/kudu#2943]
I've examined the following docs:

https://docs.microsoft.com/en-us/azure/app-service/operating-system-functionality
https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system
https://docs.microsoft.com/en-us/azure/app-service/overview-local-cache

In the article about local cache, it says that d:\home\site and d:\site\siteextensions each folder has a 300mb limit that can be increased up to 2GB.

But it also talks about d:\home\data folder, saying that files stored in d:\home\data are stored on the local VM instance and "best effor copied" to the stared store.

That leaves me with a couple of questions:

1- With all the above in mind, can our application safely store data in d:\home\data? Specifically, our app stores some cached data to disk that altough it's not critical, it's desired that in case of a deploy or any kind of restart, the information remains there, at least most of the time. I haven't read about this folder elsewhere except from the local cache documentation, so that's why I'm asking to make sure it can be used by the application.
2- What my app writes to d:\home\data will be copied to the shared store, BUT if I have other instances that information won't be available to other instances until a restart. Is that correct?
3- (edit: sorry forgot about this one) What is the size limit on d:\home\data with local cache enabled. Is it the SKU limit (ex: 50gb on Standard)? The Temporary file limit (ex: 11GB on S1)? Or something else. 
Thanks in advance.

**Comment by Deilan** [comment]
Upvote for this one to be clarified

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by christianarg** [comment]
Only took you 5 years to NOT read the question, just great

**Comment by jvano** [comment]
That is truth, this project hasn't been properly maintained for quite some time. Now, this project will be archived, so this repo will no longer be maintained.

Kudu will continue in Azure App Service. That's why we are recommending filing issues and questions directly as Azure support incidents.

Now, I will try to answer your questions:

1- With all the above in mind, can our application safely store data in d:\home\data? Specifically, our app stores some cached data to disk that although it's not critical, it's desired that in case of a deploy or any kind of restart, the information remains there, at least most of the time. I haven't read about this folder elsewhere except from the local cache documentation, so that's why I'm asking to make sure it can be used by the application.

d:\home or c:\home, both are mapped to the remote storage in our file servers and it is durable storage that you can use and it is shared across all your instances.

For non-critical stuff or for caching, I recommend you to use c:\loca\temp which is a folder only for your WebApp which is inside the Web Worker instance.

2- What my app writes to d:\home\data will be copied to the shared store, BUT if I have other instances that information won't be available to other instances until a restart. Is that correct?

All instances will be looking at the same info under d:\home or c:\home. No need to restart any instance, the changes are visible immediately as all instances are pointing to the shame remote storage folder.

3- What is the size limit on d:\home\data with local cache enabled. Is it the SKU limit (ex: 50gb on Standard)? The Temporary file limit (ex: 11GB on S1)?

The limit is based on the App Service Plan that you use. For Basic is 10 Gb of remote storage and Premium SKUs are 250 Gb. However, I recommend you to check the following link for more information:
https://azure.microsoft.com/en-us/pricing/details/app-service/windows/

I hope the info to be useful even if it was answered after all this time.

**Comment by christianarg** [comment]
Thanks
