### ISSUE TITLE
NON-persistent storage in Linux?

### ISSUE THREAD

**Issue by FISHMANPET** [projectkudu/kudu#3048]
Based on [this wiki page](https://github.com/projectkudu/kudu/wiki/Understanding-the-Azure-App-Service-file-system) hosted in this project I think this is the right place to be posing this question but if it belongs somewhere else let me know.

That wiki page mentions environment variables on Windows that can be used to find a temporary non-persistent storage location.  It also references where persistent storage is located on Linux.  Is there a location for a Linux Azure App Service container for temporary files?  Would I be safe hardcoding /tmp into my function, or is there some environment variable I can use similair to `%TMP%` in Windows?

**Comment by shshekhar** [comment]
I am not an Azure Developer but have been using the App Service on Linux. When you are on the machine the only persistent location is /home. All the files/changes outside /home will be lost once the App Service resets

**Comment by FISHMANPET** [comment]
I ended up harcoding to use /tmp/ though it's less than ideal.  It means now I _have_ to develop and test my function running on WSL, rather than running directly on my Windows machine.  If I had an environment variable that would be available that would be set in both Linux and Windows then my code would remain cross platform.

There's also no guarantee that /tmp will exist.  At the very least I'd like some assurance of what will be there on the file system for me to use.

**Comment by carson-nr** [comment]
Also not part of the Kudu team, but they must be busy since they don't seem to acknowledge issues.

So let's see what we can figure out until they can come back to this:

The way that I got around this was to use ".env" files in my local and test instances of the application.
I excluded these from my repository

literally the first thing my applications do when they start is look for a local .env file.

Then any undefined environment variables, that ARE defined in the .env, are set before anything else.
To be clear: The values in .env CANNOT override REAL environment variables.

Then in the Azure portal, go to the app service, and look for "Configuration"
![image](https://user-images.githubusercontent.com/22012608/67149554-771f9080-f27a-11e9-91cb-f6b9d0a097ba.png)

![image](https://user-images.githubusercontent.com/22012608/67149559-869ed980-f27a-11e9-912a-ca36a3dc9b64.png)

These are the environment variables when your application is deployed

so when locally developing, each developer must make or copy a ".env" file so their local application instance knows where to make/find your temp directory (windows friendly path)

*I even went as far to make my application immediately shut down if required ENV variables are not present. Still waiting to find out how I'm going to regret that decision*

then set an "Application Setting" (AKA Environment Variable) in your Linux App Service to be a Linux Friendly path

In this new paradigm of clouds, we must strive to make our applications OS agnostic.

**Comment by carson-nr** [comment]
The following code snip comes from the auto-generated deployment script when deploying with kudu

__This is specifically for a Windows app service__, **but** you can see they are just manually defining their own temp directory for deployments.

This is `.cmd` syntax

```
@if "%SCM_TRACE_LEVEL%" NEQ "4" @echo off

:: ----------------------
:: KUDU Deployment Script
:: Version: 1.0.16
:: ----------------------

:: Prerequisites
:: -------------

:: Verify node.js installed
where node 2>nul >nul
IF %ERRORLEVEL% NEQ 0 (
  echo Missing node.js executable, please install node.js, if already installed make sure it can be reached from current environment.
  goto error
)

:: Setup
:: -----

setlocal enabledelayedexpansion

SET ARTIFACTS=%~dp0%..\artifacts

IF NOT DEFINED DEPLOYMENT_SOURCE (
  SET DEPLOYMENT_SOURCE=%~dp0%.
)

IF NOT DEFINED DEPLOYMENT_TARGET (
  SET DEPLOYMENT_TARGET=%ARTIFACTS%\wwwroot
)

IF NOT DEFINED NEXT_MANIFEST_PATH (
  SET NEXT_MANIFEST_PATH=%ARTIFACTS%\manifest

  IF NOT DEFINED PREVIOUS_MANIFEST_PATH (
    SET PREVIOUS_MANIFEST_PATH=%ARTIFACTS%\manifest
  )
)

IF NOT DEFINED KUDU_SYNC_CMD (
  :: Install kudu sync
  echo Installing Kudu Sync
  call npm install kudusync -g
  IF !ERRORLEVEL! NEQ 0 goto error

  :: Locally just running "kuduSync" would also work
  SET KUDU_SYNC_CMD=%appdata%\npm\kuduSync.cmd
)
goto Deployment

:: Utility Functions
:: -----------------

:SelectNodeVersion

IF DEFINED KUDU_SELECT_NODE_VERSION_CMD (
  :: The following are done only on Windows Azure Websites environment
  call %KUDU_SELECT_NODE_VERSION_CMD% "%DEPLOYMENT_SOURCE%" "%DEPLOYMENT_TARGET%" "%DEPLOYMENT_TEMP%"
  IF !ERRORLEVEL! NEQ 0 goto error

  IF EXIST "%DEPLOYMENT_TEMP%\__nodeVersion.tmp" (
    SET /p NODE_EXE=<"%DEPLOYMENT_TEMP%\__nodeVersion.tmp"
    IF !ERRORLEVEL! NEQ 0 goto error
  )
  
  IF EXIST "%DEPLOYMENT_TEMP%\__npmVersion.tmp" (
    SET /p NPM_JS_PATH=<"%DEPLOYMENT_TEMP%\__npmVersion.tmp"
    IF !ERRORLEVEL! NEQ 0 goto error
  )

  IF NOT DEFINED NODE_EXE (
    SET NODE_EXE=node
  )

  SET NPM_CMD="!NODE_EXE!" "!NPM_JS_PATH!"
) ELSE (
  SET NPM_CMD=npm
  SET NODE_EXE=node
)

echo "NPM_CMD = !NPM_CMD!"
echo "NPM_JS_PATH = !NPM_JS_PATH!"


goto :EOF
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
