### ISSUE TITLE
Process explorer is too slow

### ISSUE THREAD

**Issue by Suchiman** [projectkudu/kudu#3059]
When there's no load on an app service, it already takes around 10 seconds to display the two processes.
If your app service plan is on fire and you're trying to figure out what's bottlenecking you (by just checking total cpu time / memory usage on the individual apps), this might take more than a minute or just fails with timeout after about 4 minutes.
Looking at the web requests it does, i'd guess there could be a lot of time saved by not retrieving advanced informations like threads and modules ahead of time to just render the grid.

And before you suggest: no i cannot use "Diagnose and solve problems", that's unavailable in azure germany.

**Comment by carson-nr** [comment]
I recommend setting custom metrics graphs directly in the Azure Portal if you can.

We had an app service peg an entire service plan at 100% cpu for 8 hours yesterday (stress test)

Things to note: I am astonished that NOTHING crashed. It all was very very slow, but not a single error was thrown from any of our applications.

Kudos (kudu's?) to Azure on that one

To find said monitoring:

Open the App Service Plan in the portal, and look for "Metrics" under monitoring

![image](https://user-images.githubusercontent.com/22012608/67150199-5b1fed00-f282-11e9-8587-1a908398ffd7.png)

This allows you to build a CUSTOM monitoring chart with just about any information you could imagine, AND pin it to your Azure Portal Dashboard for ultimate "Computer Operations Command Center Awesomeness"

https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-charts#pin-charts-to-dashboards

**Comment by Suchiman** [comment]
I'm using metrics / dashboards already, do you have a suggestion for a custom metric that would allow me to pin down which of my 30 App Services has gone crazy? The app service plan metrics are the one who tell me something is wrong but they don't point me at the guilty app service.

**Comment by NC-Development** [comment]
carson-nr (alternate account)

Right Now:
I recommend to set it up like you are about to create a graph for a single app service, and step through them one by one until something jumps out at you. Recommend smallest time intervals that it will allow. It will let you go down really small, but will start to ask for confirmation when you get really granular. I used trial an error to get it as small I could without the graph crashing. 
(Turns out portal is built with react, based on the error)

For the future:
Make setting "Dynamic Metric Alerts" part of your "new app service" workflow, and retroactively set them up for existing ones. (we just started doing this ourselves)
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/alerts-dynamic-thresholds

We set up two "Dynamic" alerts for cpu:
1. App Service High CPU (Medium Sensitivity)
2. App Service Critical CPU (Low sensitivity)

When these trigger, we get an email sent to our team.

They claim to be able to track daily, weekly, and seasonal patterns in the metrics

This is an excerpt from the above linked docs:
```
What does 'Sensitivity' setting in Dynamic Thresholds mean?
Alert threshold sensitivity is a high-level concept that controls the amount of deviation from metric behavior required to trigger an alert. This option doesn't require domain knowledge about the metric like static threshold. The options available are:

High – The thresholds will be tight and close to the metric series pattern. An alert rule will be triggered on the smallest deviation, resulting in more alerts.


Medium – Less tight and more balanced thresholds, fewer alerts than with high sensitivity (default).


Low – The thresholds will be loose with more distance from metric series pattern. An alert rule will only trigger on large deviations, resulting in fewer alerts.
```

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
