### ISSUE TITLE
ExceptionMessage":"ChangeSetId does not match

### ISSUE THREAD

**Issue by lshekarrao** [projectkudu/kudu#3063]
Hi All, I am trying to do zip deploy on Azure App Service Environment with below command.
curl -X POST -u $AZDUSERNAME:$AZDPASSWORD https://AppServiceEnvirnmentSCMURL/api/wardeploy?name=catalyst-notification1-service --data-binary @warfilepath
but I am seeing below error.
"Message":"An error has occurred.","ExceptionMessage":"ChangeSetId(release-1.0) does not match d9b1c74611e947759da28b84f1c21a07, 'master' or 'HEAD'","ExceptionType":"System.InvalidOperationException","StackTrace":"   at Kudu.Core.SourceControl.NullRepository.GetChangeSet(String id) in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\SourceControl\\NullRepository.cs:line 73\r\n   at Kudu.Core.Deployment.FetchDeploymentManager.<PerformDeployment>d__9.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Deployment\\FetchDeploymentManager.cs:line 235\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Kudu.Core.Deployment.FetchDeploymentManager.<>c__DisplayClass8_0.<<FetchDeploy>b__0>d.MoveNext() in C:\\Kudu Files\\Private\\src\\master\\Kudu.Core\\Deployment\\FetchDeploymentManager.cs:line 116\r\n--- End of stack trace from previous location where exception was thrown ---\r\n .

My repo is GITLAB and project version is release-2.0 . I build the war file as part of CI process in GITLAB on branch release-2.0. I cloned this release-2.0 branch from release-1.0.
I did verified my yml and POM file to check if there any references to release-1.0 branch but could not see any references.
Any help on this would be greatly appreciated.

Thanks,
Shekar

**Comment by carson-nr** [comment]
I am also using a private gitlab to deploy to Azure app services.

I recommend using "External Git" as your deployment method.

![image](https://user-images.githubusercontent.com/22012608/67149833-1a25d980-f27e-11e9-8c3c-d0c49f66b736.png)

0. Set up a special "Deployment" branch within your repo, with the desired deployment payload

1. in the app service, go to deployment center, select "External Git"
1. Select Kudu build service
1. Provide the "Clone with SSH" url as the source
1. Provide the name of your deployment branch
1. Assuming your repo is private, provide either your credentials, or the credentials of a neutral "deployment user" (our solution)

![image](https://user-images.githubusercontent.com/22012608/67149862-8e607d00-f27e-11e9-924c-f1a8b532651e.png)

Ok now time to tell Gitlab what the deal is:

Every app service will happily provide it's RSA key if you go to the following url
- Log in if prompted
`https://your-app.scm.azurewebsites.net/api/sshkey?ensurePublicKey=1`

NOTE: Replace `your-app` with the name of your app service

THIS (without the double quotes) is the deployment key (ssh key) you need to give to your project in gitlab, so that gitlab will allow kudu to pull. 

![image](https://user-images.githubusercontent.com/22012608/67149944-7d643b80-f27f-11e9-909e-e071fb2eaeb0.png)


That's it!

You can manually tell azure to deploy your branch by clicking the "Sync" button that is now present in the deployment center.

---

But we're lazy developers right? Why do I have to go click a thing when I JUST updated my deployment branch? Fortunately Both Azure App Services and Gitlab made this part pretty painless
---

1. On the app overview page in the Azure Portal, download publish profile
  - Look for the password in the file
  - Recommended if using vscode: 
    - set vscode to treat the file as an html file
    - apply document formatting from the command palette (F1)

2. In gitlab, in the project, go to Settings > Integrations

![image](https://user-images.githubusercontent.com/22012608/67150044-8f92a980-f280-11e9-9b3c-7474f13a21b4.png)

3. Add URL `https://$your-app:password@your-app.scm.azurewebsites.net/deploy`

4. Test:
  - Make a small change and push it into the deploy branch
  - In the deployment center make sure the deploy commit # is the same

**Comment by tonykaralis** [comment]
I am getting the same error as above. Has anyone solved the real issue here?

**Comment by nertim** [comment]
@tonykaralis Have you tried the solution suggested by @carson-nr  above? also if this is still occurring, can you please post the exception message here?

**Comment by nertim** [comment]
@tonykaralis @lshekarrao One of the reasons why you would run in to this issue is if you already have CICD configured with the app and if you try to deploy something out of band and/or change your deployment source without disconnecting. If you are still running in to this issue, we would need to collect some more information. 

But my first recommendation would be for you to disconnect and re-connect to your source control.

**Comment by tonykaralis** [comment]
@nertim Thanks for getting back to me. I did realise at the time I had configured for deployment via an external git source. Once I disconnected the zipdeploy worked. It would be great if the error messages were slightly more verbose.

Thanks though, I did get it working in the end.

**Comment by yarick123** [comment]
Hello. I am experiencing the same behavior. Previously I used "local git" deployment. Now I try to perform a zip-deployment. I have disconnected the "local git" deployment source. But the same error as above:

_ChangeSetId(azure_dev) does not match 876813da8c5c46ed8ee160b35fc4eea7, 'master' or 'HEAD'_

happens. It seems, that Kudu tries to use "local git" deployment furthermore. How could the "local git" deployment  be completely turned off?

[deploymentlog.xml.txt](https://github.com/projectkudu/kudu/files/4486146/deploymentlog.xml.txt)

**Comment by suwatch** [comment]
Remove "d:\home\site\repository" directory and retry.

**Comment by yarick123** [comment]
@suwatch thank you, unfortunately it did not help. But I solved the problem.

I had a configuration setting 

_deployment_branch=azure_dev_

After deleting it, zip-deployment started to work.

**Comment by sannayak1** [comment]
> @suwatch thank you, unfortunately it did not help. But I solved the problem.
> 
> I had a configuration setting
> 
> _deployment_branch=azure_dev_
> 
> After deleting it, zip-deployment started to work.
I couldn't find  deployment branch settings . But removing settings.xml from D:\home\site\deployments>  worked for me

**Comment by suwatch** [comment]
The common cause for this is when a site or slot have 2 conflicting types of deployments (eg. zipdeploy as well as git such as localgit or CI/CD for GitHub, etc.).   Wonder if your issue fall into this category?

**Comment by lucasa1meida** [comment]
> @tonykaralis @lshekarrao Um dos motivos pelos quais você teria esse problema é se já tiver o CICD configurado com o aplicativo e se tentar implantar algo fora da banda e / ou alterar sua fonte de implantação sem se desconectar. Se você ainda estiver enfrentando esse problema, precisaremos coletar mais algumas informações.
> 
> Mas minha primeira recomendação seria que você desconecte e reconecte ao seu controle de origem.

This works, but I don't want to have to logout every time I need to upload new code, do you know any code to automatically logout?

**Comment by lucasa1meida** [comment]
> A causa comum para isso é quando um site ou slot tem 2 tipos conflitantes de implantações (por exemplo, zipdeploy e git, como localgit ou CI / CD para GitHub, etc.). Quer saber se o seu problema se enquadra nesta categoria?

O meu acontece isso, porém eu queria que desconectasse porque toda vez que preciso mudar alguma coisa no código, ele da esse erro, e eu preciso desconectar manualmente, é possivel com algum codigo automatizar isso?

**Comment by tonykaralis** [comment]
> > @tonykaralis @lshekarrao Um dos motivos pelos quais você teria esse problema é se já tiver o CICD configurado com o aplicativo e se tentar implantar algo fora da banda e / ou alterar sua fonte de implantação sem se desconectar. Se você ainda estiver enfrentando esse problema, precisaremos coletar mais algumas informações.
> > Mas minha primeira recomendação seria que você desconecte e reconecte ao seu controle de origem.
> 
> This works, but I don't want to have to logout every time I need to upload new code, do you know any code to automatically logout?

In my case I only needed to do this one and specifically because I had previously set up a different means of deployment as @nertim had mentioned. Once I did this, I didn't have to login and do anything ever again. Perhaps you are experiencing this for different reasons.

**Comment by surenderssm** [comment]
Just happen to hit into this with a cx.
Deleting an App setting entry with "DEPLOYMENT_BRANCH" worked for us.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
