### ISSUE TITLE
Web app deployed via NodeJS to Azure but no permission to view

### ISSUE THREAD

**Issue by hoyeehong** [projectkudu/kudu#3067]
### Repro steps.
> Project built successfully on my VS Code but failed on Azure deployment
> Microsoft Visual Studio Code version 1.39.2

### Project structures.
> https://github.com/hoyeehong/TaskListApp.git

### The log/error given by the failure.
> Tried to access the web app on Azure but gotten this: "You do not have permission to view this directory or page."

### Debug your Azure website remotely.
> https://tasklistapp1.azurewebsites.net/

**Comment by suwatch** [comment]
what is the  framework required to run this type of application?  **yarn**?  My apology as I ma not familiar with this.  Linux or Windows support only or both?

**Comment by hoyeehong** [comment]
Hi @suwatch, yarn or npm.  I think Windows.

**Comment by suwatch** [comment]
I meant to run .. not to deploy.  So it is a nodejs application (since you mentioned npm).

**Comment by hoyeehong** [comment]
Yes its a nodejs application, you may use yarn start:server or yarn start:client to run.

**Comment by suwatch** [comment]
For nodejs, you need server.js file - see this https://github.com/KuduApps/NodeHelloWithNpm for example.  I am afraid the webapp is unaware of how to run yarn.

**Comment by carson-nr** [comment]
He has a `backend/server.js`, let's see if we can get things to install with just npm first. If that works, I can point you to creating your own deployment file to install yarn.

You want to set your port to the value of `process.env.PORT`, not `process.env.API_PORT`. This is the env variable Azure uses to pass your application the info for the named pipe it will use (rather than a port).

Next, the auto deployment script pulls some info from your package.json file, but it can be a little funny about a nested start file.

in package.json, under "scripts", add `"start":"node ./backend/server.js"`. and set "main" to `./backend/server.js`.

The last bit might be a bit more tricky: It looks like you have been using nodemon to run the backend while you have been developing. It also looks like nodemon has been using babel to transpile your js into the form that actually gets executed.

you do have nodemon listed as a main dependency, rather than a dev dependency. Normally nodemon is only used on the development side, but you need it so that it can apply babel. we can try to use nodemon to get you up and running, but I would recommend looking into something like `webpack` for transpiling your js code before you upload it to the app service, but one thing at a time...


last but not least, try hard not to commit "keys" to the repository, like you have in `backend/server.js`.

I recommend you set these values with more environment variables. In the final app service, you can change the environment variables in the Application Settings. For your local development, I recommend adding `dotenv` to your project, as well as a `.gitignore` file that excludes `*.env` from the repository.

This means: when someone pulls your project from the repo, they must either copy or make a `.env` file to get the secrets into the application, but the keys will be safer.

https://medium.com/the-node-js-collection/making-your-node-js-work-everywhere-with-environment-variables-2da8cdf6e786

**Comment by hoyeehong** [comment]
Thanks @carson-nr for your great advice! Now it seems like I am able to deploy to Azure as per your recommendations. However, I have amended the **port value** and **package.json** file and tried to deploy to Azure just for testing and I have gotten an issue as per below.

So I am wonder if, like you had mentioned with regards to setting environment variables, is the root cause for this issue?

![image](https://user-images.githubusercontent.com/14245325/67493148-062d0e00-f6aa-11e9-923a-5583d01064e6.png)

**Comment by carson-nr** [comment]
Sorry for the delayed response. 

That actually looks like a valid error message from Express. I would verify that you have a route defined for the "root"

If that's not the case, I'd just make sure that `app.get('port') === process.env.PORT` before you tell the server to begin listening for requests.

Yes, Azure uses the Application Setting (Environment Variable) PORT to provide the required info to connect to incoming requests.

NOTE: azure defines this as a **string naming a pipe**, rather than a number defining an actual port. I can't speak for all frameworks, but at the very least express.js will happily handle this. In my experience, the only time this has produced an error is when we had an express app checking data types, and we told it that PORT must always be a number.

Also, just to confirm: on your local working copy, with nothing running, are you able to start the project using the "node" command, or do you still require nodemon?

**Comment by hoyeehong** [comment]
Thanks for responding.

Yes, I am able to start the project with just the 'node' command.

**Comment by carson-nr** [comment]
Ok good deal, is your master branch currently up to date?

If not, I recommend creating a new branch, and pushing your current project state into that branch so I can take a look.

**Comment by kyleburnsdev** [comment]
I'm encountering what appears to be the same issue trying to deploy a minimal NodeJS application to Web App on Windows using the Quick Start at https://docs.microsoft.com/en-us/azure/app-service/app-service-web-get-started-nodejs. The application runs local just fine, but is giving "Directory Listing Denied" error after deployed using the VS Code Azure App Service extension. I'm not seeing a "PORT" environment in Kudu.

**Comment by carson-nr** [comment]
@kyleburnsdev 
The "PORT" env variable/application setting isn't exposed in the portal, but if you just `console.log(process.env.PORT)` You should get a string identifying the pipe to use rather than the port. Fortunately Express based applications (probably the http/s modules as well, but not sure) are able to use this format without modification.

**Comment by raedbenz** [comment]
@hoyeehong, how are u installing the backend dependencies like mongoose, Morgan etc. During deployment? I would expect a package.json under backend folder to be used by kudu deploy.cmd?!

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
