### ISSUE TITLE
Zipdeploy doesn't delete files no longer in the build

### ISSUE THREAD

**Issue by calvinsID** [projectkudu/kudu#3183]
> For deployment issues, please provide us with the following information:
> ---------------------------------------------------------------

### Repro steps.
- Use zipdeploy to deploy any app (I was deploying a hello world python app). I included my .env file in the zip
- Remove .env file, create new zip
- Use zipdeploy to deploy the updated app without .env file

Expected the .env file to be removed. The .env file was not removed

### Mention any other details that might be useful.

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by suwatch** [comment]
could you look at the deployment log (d:\home\site\deployments)?  it might yield some clue.

**Comment by diakonos** [comment]
I've also been running into this issue when deploying via Azure Pipelines and with the VS Code Azure extension: microsoft/azure-pipelines-tasks#13585. I've attached logs on the issue I created there.

**Comment by suwatch** [comment]
@diakonos  could you share the `deploy.sh`?  This is the script performing deployment.  There should be a step in there calling `kudusync` (code is [here](https://github.com/projectkudu/KuduSync/blob/master/bin/kudusync.js)).  

The call should take input previous and next manifests (containing the file set before and after deployment) (see [this](https://github.com/projectkudu/KuduSync#usage)).   Kudusync is using this delta to delete file in previous not present in current manifest.   Include @shrishrirang  as well.

**Comment by diakonos** [comment]
Sure, here it is: [deploy.sh.zip](https://github.com/projectkudu/kudu/files/5491441/deploy.sh.zip)

I see code for the behavior you're mentioning, but I'm not sure why it's still not overwriting wwwroot contents.

**Comment by suwatch** [comment]
@diakonos  hope you could help us dig a little deeper.  Can you look at the $NEXT_MANIFEST_PATH and $PREVIOUS_MANIFEST_PATH files as it might give you some hint?   The file differences (in PREV but not in NEXT) should be what will be deleted.

```
KUDU_SYNC_CMD=$APPDATA/npm/node_modules/kuduSync/bin/kuduSync
"$KUDU_SYNC_CMD" -v 50 $IGNORE_MANIFEST_PARAM -f "$DEPLOYMENT_SOURCE" -t "$DEPLOYMENT_TARGET" -n "$NEXT_MANIFEST_PATH" -p "$PREVIOUS_MANIFEST_PATH" -i ".git;.hg;.deployment;deploy.sh"
```

**Comment by diakonos** [comment]
Hmm.. the files seem to be exactly the same. I'm not sure if I'm checking the correct files. But I'm checking the files listed in this log:

![post_deploy_logs](https://user-images.githubusercontent.com/2521993/99024513-b87b9000-25a1-11eb-8ee6-4ea1aed28ff8.png)

They both contain the same list of files. If I add a file, it is present in both. If I remove a file, it is not present in both.

In this test, I was able to see that the file was correctly removed. However, I still see other files that are no longer in our repository but still present on the server. Perhaps there was an error at some point in the past which does not get rectified with subsequent deployments.

**Comment by shrishrirang** [comment]
If I understand you correctly, you are saying that:

- If the file being removed _is present_ in the previous manifest, you are not able to reproduce the issue because zipdeploy successfully deletes the file.
- If the file being removed _is not present_ in the previous manifest, you are able to reproduce the issue.

Is that correct?


> However, I still see other files that are no longer in our repository but still present on the server.

Can you check if those files are present in the manifest?

**Comment by diakonos** [comment]
@shrishrirang that is correct. The files that are erroneously still present on the server _are not_ in the manifest.

**Comment by shrishrirang** [comment]
> The files that are erroneously still present on the server are not in the manifest.

Ok, this explains why new deployments don't remove the files.

The files may have gone missing from the manifest either because of some error in the past or because the /home/site/deployments directory was deleted at some point of time. In either case, the mitigation will be to fix the manifest so that subsequent deployments can behave as expected.

If you want wwwroot to **exactly match** your repository (i.e. if you are **really sure** that whatever is not in the repository / zip being pushed should also be deleted from wwwroot), you can apply the following workaround. @suwatch can you think of a better way?

1. Look for `"$KUDU_SYNC_CMD" -v 50 $IGNORE_MANIFEST_PARAM ... "` in your deployment.sh
2. Temporarily change it to: `"$KUDU_SYNC_CMD" -v 50 -x ... "`.
3. Trigger a deployment. The `-x` option will ignore the manifest, thereby deleting all stale files from wwwroot. It will also generate a new manifest.
4. Now, restore deployment.sh to use the original content: `"$KUDU_SYNC_CMD" -v 50 $IGNORE_MANIFEST_PARAM ... "`

**Comment by diakonos** [comment]
Thanks for the workaround @shrishrirang. I've since changed our deployment method, but I'll keep it in mind should I ever encounter this issue again. Thank you!

**Comment by suwatch** [comment]
> The files that are erroneously still present on the server are not in the manifest.

Were the files above parts of the deployment or after deployment completion?  The whole idea of the manifest is to capture the artifact as a result of deployment.   Anything beyond, it would not know.

**Comment by diakonos** [comment]
@suwatch those files were part of the deployment. In this case we're running a Next.js application, and the files I'm referring to are pages (.js files). Pages that used to exist in our application but no longer do are still present on the server.

**Comment by suwatch** [comment]
Hope you are willing to help us debug further.  Starting with when you first deploy the app, Kudu will generate the manifest file capture files being deployed.   Do check if the manifest lists all the expected deployed files.   If not, we need to understand why first.

Then do another deployment, the previous manifest above will be used to compare with new manifest - anything in previous not in new will be deleted.    Let us know what you find.

**Comment by diakonos** [comment]
Hi @suwatch, on a fresh deployment, the manifest does list all the expected files. When a file is changed, the manifest continues to list all the files. When a file is deleted, the manifest lists all the files except that deleted file.

**Comment by aaronadamsCA** [comment]
I'm currently using the [Azure Functions GitHub Action](https://github.com/Azure/functions-action), which uses Kudu ZIP deploy.

Due to a bug in that action (https://github.com/Azure/functions-action/issues/36) my first few uploads included my entire `node_modules` directory. I had to implement a workaround to get the deployments working correctly.

Today while investigating why my function app takes 2+ minutes to restart, I was very surprised to discover it still weighs 36 MB, because the entire `node_modules` directory is still just sitting there.

If I'm being honest, the entire Azure Functions deployment chain feels very broken. I'm using TypeScript, GitHub Actions, and Azure Functions; my entire stack is Microsoft, yet none of it seems to have a _clue_ how to work together.

**Comment by suwatch** [comment]
@diakonos  is it possible to provide a repro to us? 

1) Create Linux App Service (I assumed you are using Linux).   Share all the App Settings if we need to set to get the repro especially WEBSITE_RUN_FROM_PACKAGE setting.
2) Zip Deploy this zip file (do share the zip file).
3) Do another Zip Deploy with this new zip file (also share this).   State what file is the first zip that wasn't deleted after this deployment.

We will try to use that repro to debug.   To share the file, you can create a free site and drop both zip file at that free site (assuming no secret in the zip) - tell us the file names and directory.

**Comment by diakonos** [comment]
Hi @suwatch, I tested a clean deployment on a new Azure App Service after your message from a couple weeks ago, but I wasn't able to reproduce the issue again. So unfortunately I don't have a repro to provide. I haven't been able to reproduce the issue again, I only saw evidence of the issue from the files on the server.

**Comment by suwatch** [comment]
Thanks @diakonos for the info.  Do keep us posted if you encounter one - we can then try to do the same and pinpoint the issue.

**Comment by aaronadamsCA** [comment]
(I was still seeing this behaviour without `WEBSITE_RUN_FROM_PACKAGE`, but I've now switched to `WEBSITE_RUN_FROM_PACKAGE=1`, which really seems like it should be the default for Node.js function apps! Now that I'm running directly from ZIP files, I'm no longer affected by this.)

This issue led to a LOT of confusion on my part, and did not help my Azure Functions (and TypeScript) learning curve. Being used to JS + Webpack, when I posted [this comment](https://github.com/projectkudu/kudu/issues/3183#issuecomment-739603230) I didn't understand there are parts of `node_modules` I need to deploy for my TypeScript project. That's because when I added `node_modules` to my `.funcignore` a couple of weeks ago, my app kept working fine! Little did I know the directory was still hanging around in Azure storage, it just wasn't getting updated.

I discovered my mistake weeks later, when a newly installed module was suddenly missing in production and my app went down.

Given that, I would expect you can still reproduce the issue with the following steps:

1. Initialize a "hello world" TypeScript function app that imports from `@azure/functions/Interfaces`
2. Deploy to a function app without `WEBSITE_RUN_FROM_PACKAGE`
3. Add `node_modules` to `.funcignore`
4. Deploy again

Expected behaviour would be for the app to crash due to missing imports, but that wasn't happening for me (until it did).

I don't know anything about a manifest file; my function apps were being deployed from the GitHub Action for Azure Functions. Whatever it produces, that's what my functions were using.

**Comment by maximivanov** [comment]
I stumbled upon this issue too while deploying via Azure Functions Github Action. Add a file => deploy => remove the file => deploy => the file is still there.

Environment is Linux Premium Plan.

**Comment by fkamming** [comment]
We've also seen this issue where zip deploy through Azure DevOps Pipelines leaves old files behind. **We are deploying to one staging app service slot from two different release pipelines. And we also swap staging with production app service slot upon release**. The swap obviously introduces old files which are not in previous deployment manifest, and thus are not deleted upon the next zip deployment.

We modified the pipelines to **use web deploy instead of zip deploy method**. This gives us the option to "Remove additional files at destination". This seems to address the issue.

**Comment by tslavik** [comment]
Do we have any update here? Same issue as @maximivanov with the same settings.

**Comment by 0Dmitry** [comment]
Having same issue when deploying a Node app using the Local Git option. I inspect the app deployment directory using the VSCode azure extension. If I delete some file and push to the app repository to deploy the app, after successful deploy I still can see the old files which I just have deleted in the git repo. I have added an app setting WEBSITE_RUN_FROM_PACKAGE=1 in the azure web app console for my app, but this doesn't seem to fix the issue.

**Comment by nauta008** [comment]
I'm having the same issue when deploying from the Azure App Serive VS Code plugin. I have an old typescript file which breaks the app after startup. Any update on this issue?

**Comment by LauraRocks** [comment]
We have the same issue with the zip deployment not deleting files that were in the zip in the previous deployment, but not in the current. The deleted files are still present. We are using the AzureRMWebAppDeployment@4 with RemoveAdditionalFilesFlag set as true.

**Comment by feverfunk** [comment]
Not sure if this is still active.  We had experienced functions that had been replaced (in code/project) still executing in the consumption plan.  Our issue revolved around creating a zip deploy with the same name each time in our cd pipeline.  When we switched it to use $(Build.BuildId).zip our deploys seemed to cleanup the 'phantom' functions.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
