### ISSUE TITLE
Unable to restore packages from Azure DevOps artifacts when building a .net core function app

### ISSUE THREAD

**Issue by sabrite** [projectkudu/kudu#3195]
Hey guys, I am deploying an azure function app (v3) using Azure CLI 

az functionapp deployment source config --name $functionAppName \
  --resource-group $resourceGroupName --repo-url $gitrepo \
  --branch develop \
  --git-token $token

The deployment fails because the build on Kudu side fails, when trying to restore nuget packages. The app has packages referenced through nuget and our own artifacts hosted in Azure DevOps. I have tried putting a dedicated Nuget.Config file at the root as well but it still doesnt restore.

Is there any app setting that can solve this (by pointing the feed Url)?

### Repro steps.
> The project builds fine locally and in Azure DevOps
> Using the latest MSBuild 
> Generate an access token in Azure DevOps and try to run the command I shared above with the Git url pointing to the source code repository.

Appreciate your help. Thanks,

**Comment by suwatch** [comment]
if you look at deployment - do share what command exactly failed and what was the actual error message?

**Comment by usmanibnesadiq** [comment]
The error message is like this

D:\home\site\repository\MessageProcessor.Services\MessageProcessor.Services.csproj : error NU1101: Unable to find package CAP.Logger. No packages exist with this id in source(s): nuget.org [D:\home\site\repository\MessageProcessor\MessageProcessor.csproj]

This package should not be coming from nuget.org. Instead it is hosted in Azure DevOps from where the code is being built. Since Kudu has the access token, it should be able to restore custom feeds hosted under Azure DevOps (called Artifacts) if somehow it know where to look for when restoring packages.

**Comment by usmanibnesadiq** [comment]
Just to be clear what would be the equivalent of this ("Use packages from this Azure Artifacts feed") 

![image](https://user-images.githubusercontent.com/5325072/89497672-288ab500-d800-11ea-8b78-7beca5fb3e8e.png)

when Kudu is doing automated deployment, triggered from Azure CLI?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
