### ISSUE TITLE
Support POST /api/processes/pid/kill

### ISSUE THREAD

**Issue by suwatch** [projectkudu/kudu#3228]
It will be alias to DELETE /api/processes/pid for terminating the process.   The goal is to allow it to be consistent to Azure App Service restart verb wise.

**Comment by JiriKovar** [comment]
Hi, I would like to as a question as I'm the one that raised the support ticket that ended up by creating this issue: Are the changes intended to allow the "advanced restart" functionality in Azure portal to work with delete lock present? 

I don't understand the KUDU code enough to see the connection to the advanced restart and since in the ticket I pointed out that killing one process after another is KUDU portals is our only workaround, I would not want this to be misinterpreted in a way that would lead you to remove this option. 

Thank you very much.

**Comment by suwatch** [comment]
Advanced restart internally call this API on Kudu.   The change would allow POST (in addition to DELETE) to terminate the process.  Meaning, App Service Plan with DELETE Lock can still perform advanced restart.   Note that we are not removing the DELETE api in order to avoid regression of current usages.

**Comment by JiriKovar** [comment]
Awesome! Thank you very much for clearing this up for me.
