### ISSUE TITLE
WarDeploy API results with 404

### ISSUE THREAD

**Issue by markmazan** [projectkudu/kudu#3250]
Using CURL from azure pipeline to post war file to KUDU API on app service.

Our JAVA project using war file.
It has some private jar files.
After deploying the war file using the wardeploy api endpoint some times (2/10) tomcat with the application is failing to start and results 404 error.
Catalina log says that its missing a class. The jar with the class is deployed on the server. can see it on the debug console.

WorkAround: Stop and Start the app service: without redeploy everything is working fine after restart.

**Comment by shrishrirang** [comment]
Thanks @markmazan for reporting the issue.

To help narrow down the root cause, can you use the new `/api/publish` API instead of `/api/wardeploy` and test if the 404 error goes away? `/api/publish` is a new API and is still in preview. It addresses some known issues of wardeploy.

To use `/api/publish` instead of `/api/wardeploy`, you command will change from something like this:
```bash
curl -X POST -u $cred "https://sitename.scm.azurewebsites.net/api/wardeploy" --data-binary @'./myapp.war'
```

to something like this:
```bash
curl-X POST -u $cred "https://sitename.scm.azure.websites.net/api/publish?type-war&path=webapps/ROOT" --data-binary @'./myapp.war'
```

You can find more details about this API [here].(https://github.com/shrishrirang/onedeploy/blob/9820c12339868b310602baac5f3ef0bf2d4f3327/usage/README.md)

Let us know how it goes.

**Comment by markmazan** [comment]
Hello,

The new API works well. Didn't see 404 after switching to /api/publish

**Comment by shrishrirang** [comment]
Thanks @markmazan for confirming!
