### ISSUE TITLE
[Query] Does kudu support OAuth 2.0 v2

### ISSUE THREAD

**Issue by weidongxu-microsoft** [projectkudu/kudu#3277]
Query on whether kudu supports OAuth 2.0 v2 token via MSAL to https://login.microsoftonline.com/{tenant}/oauth2/v2.0.
https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-client-creds-grant-flow#first-case-access-token-request-with-a-shared-secret

If yes, what is the "scope"? (e.g. keyvault would be https://vault.azure.net/.default, msgraph would be https://graph.windows.net/.default)

If no (and no schedule), you can close it.

Background:
Previously we uses ADAL with endpoint under e.g. `/{tenant}/oauth2/token`. Then our auth client updated to use MSAL on OAuth 2.0 v2, and we need to adopt it for kudu.
We can fallback to basic auth, but wanted to avoid it if possible.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service

**Comment by weidongxu-microsoft** [comment]
The lib changed to OAuth on 2023. So yeah, it is solved. (the question is 2021)

**Comment by jvano** [comment]
The previous message was a generic for all opened issues, but thanks for confirming this problem is solved.

This project is now deprecated and soon it will be archived, so this repo will no longer be maintained.

Kudu will continue in Azure App Service. That's why we are recommending filing issues directly as Azure support incidents moving forward.
