### ISSUE TITLE
Node 14 LTS in App Service = 10.22.0 on build

### ISSUE THREAD

**Issue by u382514** [projectkudu/kudu#3293]
I have an App Service that is configured to use Node 14 LTS (Linux web app). If I webssh into it, it will show node 14.15.1. However on the build server it uses on the deploy it says node v10.22.0 with no way of changing it since there isn't any other versions install on there apparently. I used a custom deploy.sh package to track this down and verify that the /opt/nodejs folder doesn't exist. 

What's going on here? Am I missing an important piece here? 

Also, an odd node minor version number is never an LTS version. Only even numbers...LTS is currently 14.16.1.

**Comment by royscheepens** [comment]
I am experiencing the exact same issue. According to the docs, setting the WEBSITE_DEFAULT_NODE_VERSION Application Setting to 12.18.2 should set the node version to use by the Kudu service, however this does not seem to work. This is currently breaking my build as one of the dependencies needs at least node 12.2. 

Any suggestions as how to let Kudu use a specific node version instead of v10.22.0?

**Comment by royscheepens** [comment]
@u382514 I managed to find a way to run a Node command using a different Node version in Kudu, via `benv node=14 <command>`. For instance, `benv node=14 node -v` will output `v14.15.1`. This way, you can run any Node command in the version you want, even `npx` commands (`benv node=14 npx cowsay hello`).

It seems that Kudu Service does have a lot of different Node versions installed, you can list them by running `find /opt -name node`. But somehow, Kudu Service always falls back to Node v10.22.0, even when setting environment variables like NODE_VERSION and WEBSITE_NODE_DEFAULT_VERSION, or having the App Service configured to use Node 12 or 14 🤷‍♂️

**Comment by AidanRRR** [comment]
I really don't understand why this works so buhhhh. This is a paid service? Maybe it's me, but I've spent hours upon hours on these kind of things without ever been satisfied with the outcome.

**Comment by u382514** [comment]
@AidanRRR  I ended moving the project to GCP which is a big deal because my client is not a fan of Google or Amazon. After hours upon hours of messing with Azure App Service, the client  and I lost confidence in using it for production. It’s a shame because they have some very nice features and concepts in the UI that would’ve been nice. The 14.16 node environment was actually 14.15 and a red flag. I don’t think they fully understand Nodejs release cycles and Kudu has so many open issues I’m sure they’re having a hard time keeping up. 

This service is way too expensive for these kind of simple expectations.

**Comment by suwatch** [comment]
For platform specific question (such as nodejs availability on Azure App Services or any cloud providers), we suggest to file the ticket against the service directly.

**Comment by inoue723** [comment]
I have the same issue.
It worked correctly 2 months ago.

**Comment by Sigurdlex** [comment]
I have similar problem (I chose 18 LTS, but in Kudu and thus while executing custom deployment script - 14.some.thing verstion). I did some digging and yes 'opt/nodejs' simply do not exist. I'm not a specialist in this whole deployment thing, but why? I mean it seems like a big issue, does it not? Also because of that 'selectNodeVersion.js' Kudu script throws an error, obviously. When I try diagnostic runtimes endpoint I also see this: 
<img width="742" alt="runtime 2023-12-26 19-48-39" src="https://github.com/projectkudu/kudu/assets/20502703/07571d36-84ec-4c0d-a4f1-e9017a5c123f">
which is so weird. 
I tried to create a fresh Web App (Linux, 18 LTS Node.js) and everything is completely the same. So every node.js web app doesn't have needed version of Node.js to deploy the code? Are there any tips or workarounds other than try Docker or not use Azure services?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
