### ISSUE TITLE
Q: is it possible to ignore/skip directories with ZipDeploy?

### ISSUE THREAD

**Issue by SeverinFriede** [projectkudu/kudu#3351]
I want to deploy two zips into the same AppService. The backend part should go to `/home/site/wwwroot/api` and the frontend part directly to `/home/site/wwwroot`.
This works fine when deploying the frontend first and then the backend with the `path` query param but when I deploy the frontend after the backend then the deployment deletes the `api` directory. I'm following the instructions from [here](https://docs.microsoft.com/en-us/azure/app-service/deploy-zip).

Is there a workaround for my problem? I really like to deploy backend orfrontend without  touching the other parts. With `msdeploy` this is possible by using the `-skip:Directory` parameter.

**Comment by steven-hyland** [comment]
@SeverinFriede we have used virtual directories to handle this in our use cases. https://docs.microsoft.com/en-us/azure/app-service/configure-common?tabs=portal#map-a-url-path-to-a-directory

You can have the URL mapping not necessarily follow the file & folder structure, and you should be able to deploy to specific virtual directories instead of the whole site. We use Azure Pipeline's built-in [Azure App Service Deploy Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/deploy/azure-rm-web-app-deployment?view=azure-devops) which has a `VirtualDirectory` parameter.

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
