### ISSUE TITLE
Azure Pipelines hosted agent supported platforms don't include node 16

### ISSUE THREAD

**Issue by GaryB432** [projectkudu/kudu#3377]
### Repro steps.
> add engines node >=16.0.0 to package json
> add WEBSITE_NODE_DEFAULT_VERSION = 16-lts to app configuration in portal

### Project structures.
I am deploying  a build artifact which worked with node 14.  can provide a structure if that helps.

### The log/error given by the failure.
```
Detecting node version spec...

Using package.json engines.node value: >=16.0.0

Node.js versions available on the platform are: 8.0.0, 8.1.4, 8.2.1, 8.8.1, 8.9.4, 8.11.4, 8.12.0, 8.15.1, 8.17.0, 9.4.0, 10.1.0, 10.10.0, 10.14.2, 10.21.0, 10.23.0, 12.18.2, 12.22.6, 14.17.6.

Could not resolve node version. Deployment will proceed with default versions of node and npm.

```

### Debug your Azure website remotely.
> my web-app https://ha-svelte.scm.azurewebsites.net/

### Mention any other details that might be useful.

can it be possible that I am using some old resources that don't have 16?

**Comment by HQ92** [comment]
I have a similar issue. I need to install node packages and build my app on the pipeline host that handles deployment to Azure app services. I have configured my linux app service on Azure to run Node 16, my GitHub action that prepares my app to pass to the Azure deployment action runs on Node 16, but the Azure pipeline host that runs my custom deploy.sh script to yarn install runs Node 14.

Finding the issue was a pain, but finally worked it out after checking the node version in the kudu bash for my app service. Are there plans to update this to Node 16 as well? Or is there a way that we can update Node ourselves? Currently I've managed to implement a workaround that involves building my app on my GitHub runner, zipping that up with node_modules, sending it to Azure, disabling the npm install/yarn install command so that it does not try and overwrite my node modules, and then using a pm2 script to launch my server.js.

It works, but it shouldn't be this difficult? Am I missing something? Any help would be appreciated :D

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
