### ISSUE TITLE
'org.apache.kudu.client.NonRecoverableException:' when i query kudu with presto

### ISSUE THREAD

**Issue by snake-zhiqiang** [projectkudu/kudu#3401]
Exception detail:
Query 20220916_012144_00804_8pfzk failed: org.apache.kudu.client.NonRecoverableException: cannot complete before timeout: ScanRequest(scannerId=null, tablet=42ff4e671464497e8a9bb877ab6b59b3, attempt=2, KuduRpc(method=Scan, tablet=42ff4e671464497e8a9bb877ab6b59b3, attempt=2, TimeoutTracker(timeout=30000, elapsed=30006), Trace Summary(1 ms): Sent(2), Received(1), Delayed(0), MasterRefresh(1), AuthRefresh(0), Truncated: false
 Sent: (c1af0b5ccf9f4ed9a6ef54f3047c4682, [ Scan, 1 ]), (master-192.168.171.121:7051, [ GetTableLocations, 1 ])
 Received: (master-192.168.171.121:7051, [ OK, 1 ])))

I am using jdbc to connect presto,it is successfully sometimes,but sometimes it is failed with exception

**Comment by SwjtuLyp** [comment]
Does anyone have a solution for this issue? We have ran into a similar issue too.From the log:  `GetTableLocations request on kudu.master.MasterService from 10.0.134.172:33350 dropped due to backpressure. The service queue is full; it has 2000 items. [suppressed 2633 similar messages]_`, it seems the request was dropped by kudu because of the backpressure. What could we do for that? Slow the speed of writing to Kudu?

**Comment by jvano** [comment]
Hi

If the problem persists and is related to running it on Azure App Service, please open a support incident in Azure:
https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request

This way we can better track and assist you on this case

Thanks,

Joaquin Vano
Azure App Service
